<?php

return [
    'current_version' => '1.1.41',
    'current_build' => '20260402.1',
    'history' => [
        [
            'version' => '1.1.41',
            'build' => '20260402.1',
            'released_at' => '2026-04-02',
            'title' => 'Gestión de Empresas con Switch de Contexto Operativo',
            'summary' => 'Se implementó la separación entre la edición de metadatos globales (ABM empresa) y la navegación operativa profunda dentro de otros Tenants.',
            'items' => [
                'La visualización de Gestión de Empresas permite ahora saltar e "Ingresar" directamente en la sesión operativa de otra empresa manteniéndose como admin.',
                'Se resolvieron fallos de UX por retención de sesión de Tenant 1 ("suite reaxion") al intentar ver el panel interno de terceros sin cambiar explícitamente el ancla operativa (`empresa_id`).',
            ],
        ],
        [
            'version' => '1.1.40',
            'build' => '20260401.2',
            'released_at' => '2026-04-01',
            'title' => 'Integración de Telefonía Anura con Generación de PDS',
            'summary' => 'Se implementó la recepción de webhooks de la central telefónica Anura para visualizar el historial de llamadas en el CRM. Además, se permite derivar llamadas atendidas y finalizadas (HANGUP) directamente a Pedidos de Servicio (PDS), enlazando la duración y horarios automáticamente.',
            'items' => [
                'Nuevo módulo Historial de Llamadas con filtro, papelera y ordenamiento por fecha o duración de llamada.',
                'Botón "Generar PDS" en llamadas válidas que auto-completa el diagnóstico del PDS asimilando al llamante y horarios exactos de sonado/corte.',
                'Validación de seguridad operativa que impide derivar llamadas desde internos de telefonía que no coincidan con la configuración del perfil del usuario.',
                'PDS recibe correctamente la fecha de inicio de la llamada y calcula el momento de finalización a partir de la métrica provista por la central.',
            ],
        ],
        [
            'version' => '1.1.39',
            'build' => '20260401.1',
            'released_at' => '2026-04-01',
            'title' => 'Estandarización Visual Global (Dark/Light Mode Ready)',
            'summary' => 'Se implementó una arquitectura visual robusta mediante Tokens CSS, estandarizando componentes (cards, tablas, formularios) y purgando el esquema Bootstrap legado para garantizar transiciones transparentes entre modos Claro y Oscuro en todo el sistema.',
            'items' => [
                'Expansión extensa de CSS Variables en rxn-theming.css gobernando fondos, contrastes de texto y bordes operacionales.',
                'Refactorización profunda sobre más de 15 módulos ABM quitando clases inflexibles (bg-white, text-dark) que rompían la legibilidad.',
                'Los inputs, textareas y selectores ahora asumen por defecto los fondos del motor visual para no brillar o cegar al operador en entornos oscuros.',
            ],
        ],
        [
            'version' => '1.1.38',
            'build' => '20260331.2',
            'released_at' => '2026-03-31',
            'title' => 'Restauración de Esquemas, Optimizaciones de Búsqueda y JSON Snapshots',
            'summary' => 'Se restauraron y fortalecieron integraciones perdidas: snapshots JSON de perfiles de Tango, lógica robusta de F10 en PDS, y optimizaciones de ranking en buscadores de catálogos y clientes CRM.',
            'items' => [
                'El esquema de usuarios suma resiliencia al migrar en runtime JSON snapshots faltantes de Tango Connect.',
                'Renombre del campo `falla` a `motivo_descuento` a lo largo de PDS y los reportes en Canvas Impresión.',
                'El buscador de Clientes y Artículos CRM implementa ranking por peso (Match exacto > Prefix match > Fulltext).',
                'El formulario PDS diferencia con confirmación el envío a ERP vs un guardado en borrador simple validando fecha finalizado.',
            ],
        ],
        [
            'version' => '1.1.37',
            'build' => '20260331.1',
            'released_at' => '2026-03-31',
            'title' => 'Gestión de Notas y Aislamiento de Módulos (Tenants)',
            'summary' => 'Se implementó el nuevo módulo universal de Notas CRM (con sistema propio de autocompletado de Clientes y Etiquetas), y se estabilizó un aspecto crítico de la arquitectura: el aislamiento total de sesión al cambiar de empresa.',
            'items' => [
                'Nuevo módulo "Notas CRM" con vista Read-Only diferenciada del formulario de edición, y acciones estándar (Copiar, Eliminar, Tabla con Ordenamiento).',
                'El framework CRM consolida la regla de oro Rxn: Todo panel debe permitir búsqueda asíncrona (AJAX en Vainilla JS) sin fallar el UI.',
                'Aislamiento Multi-Tenancy resuelto: editar el perfil del usuario ahora inyecta en caliente el cambio de empresa_id a la Sesión PHP, evitando fugas de información entre entornos.',
            ],
        ],
        [
            'version' => '1.1.36',
            'build' => '20260330.14',
            'released_at' => '2026-03-30',
            'title' => 'Envío Automatizado de Documentos (Mail + PDF)',
            'summary' => 'CRM ahora despacha Presupuestos y Pedidos de Servicio automáticamente mediante la configuración SMTP de la empresa, procesando on-the-fly el PDF adjunto y el cuerpo del correo desde las plantillas Canvas predefinidas.',
            'items' => [
                'Se implementó el servicio transversal DocumentMailerService orquestando MailService, PrintForms y DomPDF.',
                'Configuración Empresa suma parametrización visual explícita para designar la plantilla del cuerpo HTML y del PDF adjunto para Presupuestos y PDS.',
                'Los operadores pueden despachar un documento editable usando el botón "Enviar por mail" directamente desde la barra comercial sin abandonar el flujo.',
            ],
        ],
        [
            'version' => '1.1.35',
            'build' => '20260330.13',
            'released_at' => '2026-03-30',
            'title' => 'Hotfix: Resolución de Rutas ApiClient en Tango Connect',
            'summary' => 'Se unificó el manejo de URLs base y sufijos de endpoints a través de todos los clientes de integración Tango resguardando la conexión a la base y resolviendo un error de consulta vacía silenciosa al buscar clasificaciones PDS.',
            'items' => [
                'TangoApiClient ahora pre-procesa urls base removiendo sufijos espurios como /Api o /Api/Get introducidos desde el UI.',
                'Endpoints de lectura (Get, GetById) fueron migrados a sintaxis explícita con prefijo /Api/ para resolver colisiones de ruteo.',
                'Refactorización limpia elimina el fallo silencioso 200 OK con payload vacío en el proceso 326.',
            ],
        ],
        [
            'version' => '1.1.34',
            'build' => '20260330.12',
            'released_at' => '2026-03-30',
            'title' => 'Integración en Vivo de Clasificaciones PDS',
            'summary' => 'Se depreca el catálogo local manual estático de clasificaciones operativas remplazando el motor por una consulta en vivo interactuando bidireccionalmente contra Tango Connect usando el Process 326.',
            'items' => [
                'TangoApiClient agrega getClasificacionesPds extrayendo código visible e ID_GVA81 subyacente.',
                'PedidoServicioRepository recibe un update model layer para sostener clasificacion_id_tango de cara al futuro.',
                'El script rxn-ui del autocomplete extrae atributos ocultos silenciosos mapeando items complejos.',
                'El Payload Engine inserta un mapping directo de base para priorizar selectores seguros sobre strings crudos al remitir el PDS.',
            ],
        ],
        [
            'version' => '1.1.33',
            'build' => '20260330.11',
            'released_at' => '2026-03-30',
            'title' => 'Canvas de impresion para Pedidos de Servicio',
            'summary' => 'El modulo PDS suma la mecanica de impresion canvas ya existente en Presupuestos, con su propio contexto de variables incluyendo tiempos, diagnostico y clasificacion.',
            'items' => [
                'Se crea PedidoServicioPrintContextBuilder con grupos empresa, cliente, articulo, pedido y tiempos.',
                'PedidoServicioController incorpora printPreview siguiendo el mismo flujo que Presupuestos.',
                'PrintFormRegistry registra el documento crm_pds con objetos predeterminados listos para operar.',
                'El formulario de edicion PDS suma los botones Imprimir y Formulario en la barra de acciones.',
            ],
        ],
        [
            'version' => '1.1.32',
            'build' => '20260329.10',
            'released_at' => '2026-03-29',
            'title' => 'Cache local del perfil Tango en Configuración',
            'summary' => 'Al guardar Configuracion se sincroniza y persiste el detalle completo del perfil para usarlo en pedidos sin reconsultar a Connect.',
            'items' => [
                'empresa_config y empresa_config_crm almacenan los IDs claves, flag de moneda y snapshot JSON del perfil.',
                'El guardado de Configuración llama a Tango una sola vez y deja la fecha de sincronización visible en la UI.',
                'TangoOrderHeaderResolver consume el snapshot antes de volver a consultar y registra fallback solo si está ausente.',
            ],
        ],
        [
            'version' => '1.1.31',
            'build' => '20260329.9',
            'released_at' => '2026-03-29',
            'title' => 'Override de moneda local para company 351',
            'summary' => 'Mientras Axoft no libere el catálogo oficial de monedas, los pedidos hacia company 351 fuerzan ID_MONEDA = 2 para que Pesos no sea rechazado.',
            'items' => [
                'Se agregó un override por `tango_connect_company_id` en el resolver: company 351 ahora envía 2 como moneda local.',
                'El resto de los tenants siguen usando la heurística `MONEDA_HABITUAL`/fallback.',
                'Documentado en logs/estado como medida temporal hasta consumir el maestro real.',
            ],
        ],
        [
            'version' => '1.1.30',
            'build' => '20260329.8',
            'released_at' => '2026-03-29',
            'title' => 'Resolver forzado a usar la URL Posta de Connect',
            'summary' => 'El resolver de cabecera corrige la URL base de Axoft (agregando /Api o usando la llave) para poder bajar el detalle del perfil y evitar talonarios/monedas en fallback.',
            'items' => [
                'Si el operador guardó `https://000357-014.connect.axoft.com` sin `/Api`, el resolver lo normaliza antes de llamar a `GetById`.',
                'Con esto, `ID_GVA43_TALON_PED` vuelve a salir del perfil real y no del legacy 6 en empresas que usan company 351.',
                'La heurística de moneda (`C => 1 / resto => 0`) ahora se evalúa con datos reales del perfil porque la consulta ya no devuelve nulo.',
            ],
        ],
        [
            'version' => '1.1.29',
            'build' => '20260329.7',
            'released_at' => '2026-03-29',
            'title' => 'Heuristica temporal de moneda por perfil Tango',
            'summary' => 'PDS y pedidos web ya leen `MONEDA_HABITUAL` del perfil para decidir `ID_MONEDA`, aplicando la regla local vs extranjera documentada mientras esperamos el catalogo oficial.',
            'items' => [
                'TangoOrderHeaderResolver mapea `MONEDA_HABITUAL = C` a `ID_MONEDA = 1` (pesos) y cualquier otro flag a `ID_MONEDA = 0`, dejando fallback legacy solo si el perfil no expone dato.',
                'TangoOrderMapper acepta valores cero para `ID_MONEDA`, evitando que el normalizador legacy descarte la moneda extranjera.',
                'Se deja registrada la heuristica bimonetaria en docs para revisar cuando Tengamos el endpoint real de monedas (process 16660 o equivalente).',
            ],
        ],
        [
            'version' => '1.1.28',
            'build' => '20260329.6',
            'released_at' => '2026-03-29',
            'title' => 'Hotfix del perfil Tango y resolver inicial de pedidos',
            'summary' => 'Configuracion vuelve a cargar perfiles habilitados reales desde Tango y los pedidos de Tiendas/CRM empiezan a resolver su cabecera comercial a partir del perfil seleccionado.',
            'items' => [
                'El selector `Perfil de pedido Tango` corrige la carga/search sobre `process=20020` usando `view=Habilitados` y los campos reales del catalogo.',
                'Pedidos Web y Pedidos de Servicio CRM usan un resolver compartido para poblar `ID_PERFIL_PEDIDO`, talonario y demas IDs de cabecera desde el detalle del perfil.',
                'Se mantienen fallbacks legacy acotados para talonario, deposito y moneda mientras se completa la migracion del resto de consumidores.',
            ],
        ],
        [
            'version' => '1.1.27',
            'build' => '20260329.5',
            'released_at' => '2026-03-29',
            'title' => 'Configuracion unifica Perfil de pedido Tango',
            'summary' => 'Tiendas y CRM dejan de exponer listas, deposito y talonario en Configuracion, usando un unico selector de perfil de pedido alimentado por Tango Connect `process=20020`.',
            'items' => [
                'EmpresaConfig suma el selector compartido `Perfil de pedido Tango` con persistencia por area y snapshot local de codigo/descripcion.',
                'La recarga de metadata por empresa Connect ya no consulta listas/deposito en este flujo y consume solo empresas + perfiles de pedido.',
                'Se preservan los campos legacy en base para no romper consumidores existentes mientras se planifica la migracion de payloads.',
            ],
        ],
        [
            'version' => '1.1.26',
            'build' => '20260329.4',
            'released_at' => '2026-03-29',
            'title' => 'Formularios imprimibles con tablas repetitivas',
            'summary' => 'El motor de impresion suma soporte para bloques repetitivos (items), completando la primera version operativa del documento de presupuesto.',
            'items' => [
                'El canvas editor ahora soporta el objeto `table_repeater` para iterar renglones de documentos.',
                'Las tablas son visualmente ajustables y persisten sus columnas, anchos y estilos en JSON.',
                'Presupuestos CRM inaugura el circuito de impresion con un boton "Imprimir" que abre la version renderizada lista para el navegador.',
                'El contexto de impresion se aplanó y estandarizó para facilitar el diseño del documento.',
            ],
        ],
        [
            'version' => '1.1.25',
            'build' => '20260329.3',
            'released_at' => '2026-03-29',
            'title' => 'Correccion en PDS por widget de bitacora',
            'summary' => 'Se resolvio un error interno que impedia abrir el formulario de Pedidos de Servicio cuando el modulo tenia notas con imagenes adjuntas registradas por administradores.',
            'items' => [
                'Se aislaron las variables internas del widget de bitacora compartida para evitar colisiones con las pantallas operativas.',
                'El formulario de Pedidos de Servicio vuelve a renderizar correctamente en todos los casos sin importar el historial de notas.',
            ],
        ],
        [
            'version' => '1.1.24',
            'build' => '20260329.2',
            'released_at' => '2026-03-29',
            'title' => 'PDS corrige fecha actual y suma borrado de capturas',
            'summary' => 'Pedidos de Servicio estabiliza la funcionalidad del reloj en tiempo real para las fechas y permite eliminar imagenes que ya estaban guardadas.',
            'items' => [
                'El checkbox de ahora funciona correctamente tanto en Inicio como en Finalizado actualizando los inputs.',
                'Se agrega el boton para eliminar las capturas que ya estaban subidas a disco y limpiar el PDS.',
            ],
        ],
        [
            'version' => '1.1.23',
            'build' => '20260329.1',
            'released_at' => '2026-03-29',
            'title' => 'Sincronizacion tolerante a multiples sucursales',
            'summary' => 'La sincronizacion de clientes CRM desde Tango ahora soporta multiples clientes o sucursales que comparten el mismo correo electronico bajo una sola empresa.',
            'items' => [
                'Se elimino la restriccion estricta que impedia tener correos electronicos duplicados para clientes de una misma empresa.',
                'El proceso de sincronizacion ya no aborta al recibir multiples sucursales con el mismo email comercial.',
                'La actualizacion repara automaticamente la base de datos local en las instalaciones existentes.',
            ],
        ],
        [
            'version' => '1.1.22',
            'build' => '20260328.24',
            'released_at' => '2026-03-28',
            'title' => 'Canvas de impresion base y editor visual A4',
            'summary' => 'La plataforma suma la base persistente de formularios de impresion y un primer editor visual A4 para Presupuesto CRM, con fondo, fuentes, objetos posicionados y versionado.',
            'items' => [
                'Se agrega el modulo Formularios de Impresion dentro del CRM con listado y editor visual propio.',
                'El canvas editable soporta fondo, texto fijo, variables, lineas, rectangulos y fuentes desde una whitelist controlada.',
                'Las definiciones se guardan como versiones persistentes con assets y JSON estructurado, en lugar de HTML suelto.',
                'Presupuesto CRM ya puede enlazarse con una mecanica documental estandar de la plataforma sin depender de CrystalReports.',
            ],
        ],
        [
            'version' => '1.1.21',
            'build' => '20260328.23',
            'released_at' => '2026-03-28',
            'title' => 'PDS libera mejor el diagnostico y suma hora actual',
            'summary' => 'Pedidos de Servicio baja el bloque de pegado de imagenes debajo del diagnostico, achica miniaturas y agrega un check para capturar la hora actual al finalizar.',
            'items' => [
                'El bloque de pegado de imagenes deja de quedar arriba del diagnostico.',
                'Las miniaturas del diagnostico se compactan un poco mas.',
                'Finalizado puede tomar la fecha y hora actual con un checkbox sin tipear manualmente.',
            ],
        ],
        [
            'version' => '1.1.20',
            'build' => '20260328.22',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion afina Connect y sus catalogos',
            'summary' => 'Configuracion restaura bien el estado visual del boton Connect y extiende la busqueda asistida a listas y deposito para acelerar la seleccion operativa.',
            'items' => [
                'El boton de metadata ya no queda trabado en Resolviendo descripciones tras cambiar de empresa.',
                'Lista 1, Lista 2 y Deposito suman buscadores con sugerencias locales sobre la metadata cargada.',
                'Tiendas y CRM reciben el mismo ajuste al compartir la pantalla de Configuracion.',
            ],
        ],
        [
            'version' => '1.1.19',
            'build' => '20260328.21',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion reengancha bien los catalogos Connect',
            'summary' => 'Configuracion vuelve a enviar el formulario correcto en sus llamadas AJAX, por lo que la empresa Connect seleccionada alimenta otra vez la carga de listas y deposito.',
            'items' => [
                'El JS de Configuracion ahora serializa explicitamente `#empresa-config-form`.',
                'La empresa Connect elegida vuelve a viajar en la recarga de metadata y destraba listas/deposito.',
                'El ajuste impacta tanto en Tiendas como en CRM al compartir la misma pantalla.',
            ],
        ],
        [
            'version' => '1.1.18',
            'build' => '20260328.20',
            'released_at' => '2026-03-28',
            'title' => 'PDS ordena mejor sus previews de diagnostico',
            'summary' => 'Pedidos de Servicio mueve el preview temporal de capturas debajo del diagnostico, reduce el tamaño de miniaturas y evita duplicar numeracion por etiquetas viejas.',
            'items' => [
                'El preview de imagenes pegadas deja de aparecer en la caja superior y pasa debajo del textarea Diagnostico.',
                'Las miniaturas del diagnostico se achican para ocupar menos espacio operativo.',
                'El siguiente #imagenN ahora contempla etiquetas historicas con o sin numeral para no repetir numeracion.',
            ],
        ],
        [
            'version' => '1.1.17',
            'build' => '20260328.19',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion afina el buscador de empresa Connect',
            'summary' => 'El buscador de empresa Connect gana una presentacion mas clara con icono, placeholder guiado y feedback visible de la empresa seleccionada.',
            'items' => [
                'La entrada visible de empresa Connect queda mas alineada con el patron de busqueda del resto del sistema.',
                'Una pill de estado muestra si hay empresa elegida y cual quedo activa.',
                'El flujo operativo sigue siendo el mismo para Tiendas y CRM porque ambos comparten la pantalla de Configuracion.',
            ],
        ],
        [
            'version' => '1.1.16',
            'build' => '20260328.18',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion mejora empresa Connect y catalogos',
            'summary' => 'Configuracion ya no consulta listas y depositos sin empresa valida, y el selector de empresa Connect suma busqueda con sugerencias para agilizar la eleccion.',
            'items' => [
                'La validacion inicial de Connect trae el maestro de empresas y deja los catalogos dependientes para cuando haya una empresa seleccionada.',
                'Elegir una empresa desde el buscador visible dispara la carga correcta de listas de precio y deposito.',
                'El ajuste aplica a Tiendas y CRM porque ambos comparten la misma pantalla de configuracion.',
            ],
        ],
        [
            'version' => '1.1.15',
            'build' => '20260328.17',
            'released_at' => '2026-03-28',
            'title' => 'PDS compacta su bloque tecnico',
            'summary' => 'Pedidos de Servicio reubica su fila operativa dentro del detalle tecnico y hace que las miniaturas del diagnostico ocupen menos espacio visual.',
            'items' => [
                'Solicito, Pedido Tango y Articulo bajan al bloque tecnico para liberar la parte alta del formulario.',
                'Las miniaturas del diagnostico ya no dejan una franja ancha inutil cuando hay pocas imagenes.',
                'Se sostiene la experiencia compacta del PDS sin meter dependencias nuevas.',
            ],
        ],
        [
            'version' => '1.1.14',
            'build' => '20260328.16',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion alinea selectores con empresa Connect',
            'summary' => 'Tiendas y CRM ahora recargan listas y deposito al cambiar la empresa Connect, evitando guardar combinaciones comerciales inconsistentes.',
            'items' => [
                'Cambiar la empresa Connect recompone en cascada Lista 1, Lista 2 y Deposito dentro de Configuracion.',
                'El backend rechaza guardados si la empresa cambio pero los selectores dependientes quedaron sin refrescar.',
                'La correccion aplica tanto a Tiendas como a CRM porque ambos comparten el modulo EmpresaConfig.',
            ],
        ],
        [
            'version' => '1.1.13',
            'build' => '20260328.15',
            'released_at' => '2026-03-28',
            'title' => 'Presupuestos CRM con pantalla operativa usable',
            'summary' => 'CRM suma una primera pantalla util de presupuestos con cabecera comercial, autocompletado por cliente, renglones acumulables y base local preparada para crecer hacia impresion y versionado.',
            'items' => [
                'Se agrega el modulo Presupuestos CRM con listado, alta y edicion propias dentro del dashboard CRM.',
                'La cabecera comercial se autocompleta desde clientes CRM y catalogos cacheados localmente por empresa.',
                'El detalle se arma por renglones editables buscando articulos CRM por codigo o descripcion.',
                'Cabecera, items y totales quedan persistidos como snapshots locales para no romper historicos.',
            ],
        ],
        [
            'version' => '1.1.12',
            'build' => '20260328.14',
            'released_at' => '2026-03-28',
            'title' => 'PDS toma clasificaciones desde Configuracion CRM',
            'summary' => 'Configuracion CRM suma un catalogo local de clasificaciones y el selector del PDS pasa a consumirlo sin depender de un endpoint externo.',
            'items' => [
                'Configuracion CRM incorpora un textarea para pegar clasificaciones operativas del PDS.',
                'El selector Clasificacion del PDS busca por codigo o descripcion sobre ese catalogo interno.',
                'Los PDS guardan snapshot de codigo y descripcion de clasificacion para preservar historico.',
            ],
        ],
        [
            'version' => '1.1.10',
            'build' => '20260328.12',
            'released_at' => '2026-03-28',
            'title' => 'PDS valida mejor las respuestas de Tango',
            'summary' => 'Pedidos de Servicio estabiliza sus rutas de Connect, detecta rechazos semanticos aunque el HTTP sea 200 y deja trazabilidad mas fiel del estado real del envio.',
            'items' => [
                'TangoOrderClient alinea rutas `/Api/Create` y `/Api/GetByFilter` con el resto del stack.',
                'El envio PDS ya no toma como exitoso un `succeeded=false` de Connect.',
                'La prueba real del PDS confirmó que `ID_STA11` ya se resuelve y que el bloqueo actual está en la configuración comercial del artículo dentro de Tango.',
            ],
        ],
        [
            'version' => '1.1.9',
            'build' => '20260328.11',
            'released_at' => '2026-03-28',
            'title' => 'PDS con monitor de tiempo mas presente',
            'summary' => 'Pedidos de Servicio compacta mas su layout tecnico y deja el monitor de tiempos mucho mas visible mientras se carga el trabajo.',
            'items' => [
                'Se reducen espacios entre inputs y la altura visible de Diagnostico/Falla.',
                'El bloque de tiempos queda mas cerca del detalle tecnico y se sostiene visible en desktop.',
                'Las miniaturas del diagnostico permanecen debajo del textarea sin romper el seguimiento operativo.',
            ],
        ],
        [
            'version' => '1.1.8',
            'build' => '20260328.10',
            'released_at' => '2026-03-28',
            'title' => 'Store con toggle frontal y ofertas por articulo',
            'summary' => 'La tienda publica ahora alterna entre categorias y catalogo, el detalle vuelve con contexto y cada articulo de Tiendas puede mostrar una oferta comercial usando Lista 2 como precio promocional.',
            'items' => [
                'El Store permite alternar entre vista de categorias y vista de catalogo desde el frente.',
                'El detalle de producto incorpora un boton de vuelta contextual al recorrido previo.',
                'Tiendas suma un switch local por articulo para publicar oferta con badge y precio tachado.',
                'Carrito y checkout respetan el precio promocional cuando la oferta esta activa.',
            ],
        ],
        [
            'version' => '1.1.7',
            'build' => '20260328.9',
            'released_at' => '2026-03-28',
            'title' => 'PDS afina lookup Tango y miniaturas de diagnostico',
            'summary' => 'Pedidos de Servicio mejora la resolucion de ID_STA11 al enviar a Tango y alinea las capturas del diagnostico con la visual compacta de la bitacora.',
            'items' => [
                'El lookup de ID_STA11 ahora tolera variantes del codigo y distintas estructuras de respuesta de Connect.',
                'Las capturas pegadas en Diagnostico se muestran como miniaturas chicas debajo del textarea.',
                'Se sostiene la mecanica local-first del PDS sin depender de busquedas remotas al seleccionar articulo.',
            ],
        ],
        [
            'version' => '1.1.6',
            'build' => '20260328.8',
            'released_at' => '2026-03-28',
            'title' => 'Backoffice con usuario visible y acceso rapido a tienda',
            'summary' => 'El backoffice ahora identifica al usuario activo en cabecera y resuelve un acceso directo a la tienda publica asociada a su empresa cuando existe.',
            'items' => [
                'Las cabeceras principales del backoffice muestran `Hola, {usuario}` para dar contexto inmediato de sesion.',
                'Si la empresa actual tiene Tiendas habilitado, esta activa y posee slug, aparece un boton para abrir su tienda publica.',
                'Cuando no existe una tienda publica valida, el backoffice informa el motivo en lugar de exponer un enlace inconsistente.',
            ],
        ],
        [
            'version' => '1.1.5',
            'build' => '20260328.7',
            'released_at' => '2026-03-28',
            'title' => 'PDS estable con capturas en diagnostico',
            'summary' => 'Pedidos de Servicio estabiliza su guardado/envio a Tango y suma capturas pegadas en Diagnostico con referencias internas reutilizables.',
            'items' => [
                'Se corrige el fallo de persistencia que rompia el update del PDS al guardar cambios.',
                'Diagnostico admite capturas pegadas desde portapapeles y las referencia como #imagenN.',
                'Los adjuntos del PDS quedan guardados en disco y persistidos en una tabla propia del modulo.',
            ],
        ],
        [
            'version' => '1.1.4',
            'build' => '20260328.6',
            'released_at' => '2026-03-28',
            'title' => 'Clientes CRM cacheados desde Tango',
            'summary' => 'Clientes CRM deja de reutilizar el ABM manual de Tiendas y pasa a operar con una cache local sincronizable desde Tango/Connect, alineada al patron de Articulos CRM.',
            'items' => [
                'Clientes CRM ahora lista, busca, pagina y edita sobre `crm_clientes` como cache local propia del entorno.',
                'Se agrega `Sync Clientes` desde CRM para persistir y actualizar clientes Tango/Connect (process 2117).',
                'Pedidos de Servicio consume la nueva tabla local de clientes CRM sincronizados para sugerencias y envio a Tango.',
            ],
        ],
        [
            'version' => '1.1.3',
            'build' => '20260328.5',
            'released_at' => '2026-03-28',
            'title' => 'Clientes CRM independientes',
            'summary' => 'CRM suma su propia base de clientes independiente, con la misma experiencia de validacion y persistencia validada en Tiendas.',
            'items' => [
                'Se implementó Clientes CRM en entorno independiente, replicando la UX de resolucion de Tango.',
                'Pedidos de Servicio ahora asocia y sugiere clientes usando la base local propia del CRM.',
                'Aislamiento completo de relaciones comerciales de clientes entre ambos entornos operativos.',
            ],
        ],
        [
            'version' => '1.1.2',
            'build' => '20260328.4',
            'released_at' => '2026-03-28',
            'title' => 'Bitacora en dock minimizado y recuperacion mas rapida',
            'summary' => 'La bitacora deja de colapsar como tarjeta grande y pasa a un dock chico abajo a la derecha, restaurando despues su layout expandido previo.',
            'items' => [
                'El estado minimizado ahora se ve como un dock compacto y no como una ventana deformada.',
                'Al restaurar, la bitacora recupera posicion y tamaño expandido anteriores.',
                'Se suma un launcher minimo para reabrir rapido el panel desde la esquina inferior derecha.',
            ],
        ],
        [
            'version' => '1.1.1',
            'build' => '20260328.3',
            'released_at' => '2026-03-28',
            'title' => 'Bitacora minimizable y refinamiento interno de ergonomia',
            'summary' => 'La bitacora flotante ahora puede minimizarse como una ventana compacta, conservando su tamaño expandido para volver al trabajo sin reacomodarla.',
            'items' => [
                'La bitacora suma un estado minimizado prolijo, mas cercano a una ventana reducida que a un panel deformado.',
                'El layout del widget conserva el tamaño expandido previo y lo restaura al volver a abrirlo.',
                'El header minimizado tambien permite restaurar rapido la bitacora sin romper el flujo del modulo.',
            ],
        ],
        [
            'version' => '1.1.0',
            'build' => '20260328.2',
            'released_at' => '2026-03-28',
            'title' => 'Split operativo Tiendas/CRM con categorias y primer CRM real',
            'summary' => 'La base operativa se expande con categorias comerciales en Store, separacion funcional entre Tiendas y CRM, configuracion CRM propia y el primer modulo operativo del circuito CRM.',
            'items' => [
                'Tiendas incorpora categorias locales con filtro publico y asignacion por SKU persistente.',
                'Launcher y dashboards separan Tiendas y CRM segun flags reales del tenant.',
                'CRM ya cuenta con configuracion operativa propia y servicios preparados por area.',
                'Se suma Pedidos de Servicio como primer modulo operativo real del entorno CRM.',
            ],
        ],
        [
            'version' => '1.0.0',
            'build' => '20260328.1',
            'released_at' => '2026-03-28',
            'title' => 'Base operativa con versionado visible',
            'summary' => 'Se formaliza una fuente unica de version y se publica un bloque de Novedades visible para operadores y clientes.',
            'items' => [
                'Se centralizo la version activa del sistema en una unica configuracion interna.',
                'La tienda publica ahora muestra un bloque Novedades con la release vigente.',
                'Launcher y dashboards exponen la misma version para evitar desalineaciones operativas.',
            ],
        ],
    ],
];
