<?php

return [
    'current_version' => '1.3.4',
    'current_build' => '20260410.3',
    'history' => [
        [
            'version' => '1.3.4',
            'build' => '20260410.3',
            'released_at' => '2026-04-10',
            'title' => 'RxnSync: Persistencia de filtros por solapa y mejoras de UX',
            'summary' => 'Los filtros del módulo RxnSync ahora persisten al cambiar entre las solapas Clientes y Artículos: el filtro Motor BD (server-side), los embudos de columna (client-side) y los inputs de búsqueda se restauran automáticamente al volver a una solapa. SyncPrecios y SyncStock redirigen de vuelta a RXN-Sync con detalle de stats. Se eliminó el botón redundante Sync Artículos.',
            'items' => [
                'Persistencia de filtros Motor BD por solapa: los URLSearchParams del tab saliente se guardan en memoria y se restauran al volver, recargando los datos filtrados via AJAX.',
                'Persistencia de embudos client-side: los filtros de columna (op + valor) y el estado del input de búsqueda sobreviven cambios de solapa.',
                'SyncPrecios y SyncStock redirigen de vuelta a RXN-Sync en lugar de Artículos, mostrando el detalle de la sincronización (recibidos, insertados, actualizados, omitidos).',
                'Botón Sync Artículos eliminado del circuito de RxnSync — la Auditoría del tab activo cumple la misma función sin salir del módulo.',
            ],
        ],
        [
            'version' => '1.3.3',
            'build' => '20260410.2',
            'released_at' => '2026-04-10',
            'title' => 'RxnSync: Filtro Motor BD integrado (AJAX mode)',
            'summary' => 'Se integró el sistema de Filtro Motor BD al módulo RxnSync. Las columnas Estado, Código y Nombre del tab de Artículos y Clientes ahora soportan filtrado Motor BD con fetch AJAX (sin redirección), preservando la experiencia de pestañas. El sistema rxn-advanced-filters fue refactorizado para soportar modo AJAX con reinicialización post-fetch.',
            'items' => [
                'RxnSync Artículos y Clientes: columnas Estado, Código y Nombre ahora tienen ícono de filtro Motor BD + Selección Local.',
                'Modo AJAX: al aplicar un filtro Motor BD en RxnSync, el contenido del tab se recarga vía fetch sin navegar fuera de la página ni romper la experiencia de pestañas.',
                'history.pushState sincroniza la URL con los parámetros del filtro activo para que el ícono se muestre correctamente.',
                'rxn-advanced-filters.js refactorizado: expuesto como window.rxnFiltersInit(), re-ejecutable post-AJAX con guard data-rxn-filter-init.',
            ],
        ],
        [
            'version' => '1.3.2',
            'build' => '20260410.1',
            'released_at' => '2026-04-10',
            'title' => 'Filtro Avanzado: Selección Local + Mejoras CRM',
            'summary' => 'Se potenciaron los filtros de columna en todos los módulos CRUD con una nueva sección de Selección Local (filtrado client-side por valores únicos), persistente via sessionStorage. Se incluyeron mejoras de configuración de empresa, presupuestos Tango y correcciones generales de UX.',
            'items' => [
                'Filtros de columna ahora incluyen Selección Local: checkboxes de valores únicos con conteo, búsqueda dentro de la lista, Marcar Todo / Ninguno y persistencia automática de la selección durante la sesión.',
                'Motor BD y Selección Local coexisten en el mismo popover: el Motor BD ejecuta queries en servidor, la Selección Local filtra las filas cargadas en el cliente. Ambos estados se reflejan en el ícono de columna.',
                'Soporte multi-columna: los filtros locales de múltiples columnas se combinan correctamente — una fila se oculta si cualquiera de los filtros activos la excluye.',
                'Mejoras de configuración de empresa, módulo de presupuestos con campos Tango, correcciones de UX en CRM y ajustes de estabilidad general.',
            ],
        ],
        [
            'version' => '1.3.1',
            'build' => '20260407.5',
            'released_at' => '2026-04-07',
            'title' => 'Tango Sync ID_GVA81 y Estabilidad de UX',
            'summary' => 'Se establecieron correciones críticas de usabilidad para las ventanas modales CRM y se integró correctamente la parametrización de Clasificación (ID_GVA81) para sincronizar presupuestos a Tango.',
            'items' => [
                'El mapeo para la sincronizacion a la API de Tango ahora asimila el ID_GVA81 extraído de los selectores asíncronos y catalógo local.',
                'Reparación profunda del manejador central global del evento Escape: los sub-componentes (Spotlight, Listados AJAX) interceptan y destruyen el evento antes de llegar a la ventana principal logrando así no disparar indeseablemente las alertas de "Salir sin Guardar".',
                'El clonado de Presupuestos desde el ABM ya no borra el caché de metadata comercial (`deposito_nombre_snapshot`, `lista_nombre_snapshot`, etc) asegurando fidelidad histórica entre copias.',
            ],
        ],
        [
            'version' => '1.3.0',
            'build' => '20260407.4',
            'released_at' => '2026-04-07',
            'title' => 'Spotlight Mode Unificado CRM',
            'summary' => 'Se introdujo el buscador universal flotante (Global Spotlight Modals) para búsquedas instantáneas e integradas abarcando tanto Artículos o Clientes asíncronos como toda clase de Selectores clásicos nativos dentro del CRM.',
            'items' => [
                'Activación Inmediata con teclado: El operador logra apretar Enter frente o pararse sobre virtualmente todo campo seleccionable (Condición de Venta, Vendedores, Transportes) abriéndose un panel envolvente.',
                'Motor Inteligente Predictivo: Permite capturar e indagar catálogos estáticos enteros precargados localmente (sin llamadas al backend) o mutar a asíncrono para bases masivas.',
                'Prioridad Activa en Capture Phase: El Spotlight reclama los eventos de teclado para evitar envíos fortuitos de formulario durante selección rápida.',
                'Se redefinió visualmente el contraste (Dark y Light Mode) sobre módulos Presupuestarios, junto con reparaciones funcionales del historial SQL (PDO bindings).',
            ],
        ],
        [
            'version' => '1.2.9',
            'build' => '20260407.3',
            'released_at' => '2026-04-07',
            'title' => 'RXN Live: Ordenamiento Correcto de Fechas y Estabilidad de Contenedores',
            'summary' => 'Se corrigió el ordenamiento de columnas de tipo fecha en todos los informes de RXN Live (afectaba a todos los datasets), y se estabilizó la altura mínima de los contenedores de tabla para evitar el recorte del panel de filtros avanzados.',
            'items' => [
                'Fix ordenamiento de fechas: parseFloat("2026-03-29") devuelve 2026 (año solo), haciendo que todas las fechas del mismo año compararan igual. El sort ahora detecta columnas date/datetime via pivotMetadata y compara el string ISO original que ordena lexicográficamente de forma correcta.',
                'Mejora sort numérico: se agregó isFinite() como guardia adicional para evitar falsos positivos en el detector numérico.',
                'Mejora sort textual: localeCompare con locale "es" y sensitivity "base" para respetar correctamente ñ y acentos del español.',
                'Los valores nulos/vacíos siempre se ubican al fondo de la lista ordenada, en ambas direcciones.',
                'min-height: 520px en contenedores #plana y #pivotResultContainer para que el dropdown de filtros avanzados (~430px) no quede recortado cuando hay pocos registros.',
            ],
        ],
        [
            'version' => '1.2.8',
            'build' => '20260407.2',
            'released_at' => '2026-04-07',
            'title' => 'RXN Live: Resurrección Total del Motor JS',
            'summary' => 'Se erradicaron tres bugs críticos que dejaban el módulo RXN Live completamente en blanco en todos los datasets: un template literal JS sin cerrar que mataba todo el script, un conflicto de z-index entre el dropdown de filtros y la fila TOTAL sticky, y corrupción de diccionarios internos al hidratar vistas guardadas.',
            'items' => [
                'Fix CRÍTICO: template literal `buildDiscreteDropdown()` sin cerrar — un \\` (backslash-backtick) escapado dentro del template impedía que el parser JS encontrara el cierre, haciendo que DOMContentLoaded nunca se ejecutara y la pantalla quedara en blanco total.',
                'Fix z-index: el dropdown de filtros avanzados ya no queda tapado por la fila TOTAL (tfoot sticky). Dropdown sube a z-index:1050, tfoot baja a z-index:1.',
                'Fix robustez de estado: flatFilters y flatDiscreteFilters se inicializan con verificación de tipo (typeof === "object") al hidratar desde sessionStorage, evitando TypeErrors silenciosos que interrumpían renderPlana().',
                'Fix HTML: se restauró el </div> faltante del wrapper externo en el panel de Selección Local del dropdown de filtros.',
                'Fix selector de vista: el atributo selected se aplica desde PHP usando view_id de la URL para que el dropdown de vistas refleje la vista activa desde el primer render del servidor.',
            ],
        ],
        [
            'version' => '1.2.7',
            'build' => '20260407.1',
            'released_at' => '2026-04-07',
            'title' => 'Carga Rápida de Presupuestos por Teclado',
            'summary' => 'Refactorización de la interfaz de carga de presupuestos en el CRM para permitir a los operadores una carga de artículos ultra rápida "inline" utilizando atajos de teclado y campos reactivos de alta precisión.',
            'items' => [
                'Se implementó una barra de adición ágil en `Presupuestos CRM` que permite configurar cantidad, precio y bonificación del artículo elegido antes de volcarlo al documento.',
                'Navegabilidad "Chau Ratón": soporta transiciones íntegras vía `TAB` y la inyección final del renglón directamente apretando `Enter`.',
                'El importe temporal neto se recalcula de forma reactiva a la visual del operador.',
                'Se incorporó contenido operativo avanzado en el Centro de Ayuda del sistema para enseñar estos atajos tácticos y explicar en profundidad la incidencia del botón "Sync Catálogos".',
            ],
        ],
        [
            'version' => '1.2.6',
            'build' => '20260406.7',
            'released_at' => '2026-04-06',
            'title' => 'RXN Live: Corrección de Bucles de URL y Botón de Actualizar',
            'summary' => 'Se erradicó el error de "parpadeo infinito" al aplicar filtros sobre campos temporales, estabilizando el HistoryState de la plataforma frente al comportamiento asíncrono de persistencia volátil.',
            'items' => [
                'Reparación profunda del Session Storage: los parámetros inyectados de filtrado de BD ahora se cachean en memoria volátil instantes previos al redirect (Push), evitando el "Efecto Bumerán" con viejos valores almacenados prematuramente en el DOM Tree.',
                'Refactorización del método de permuta de Vista Guardada: se previene la reescritura innecesaria evitando validaciones sucias del LoadSelectedView.',
                'Inclusión de acceso rápido Alt+A (Botón de Acción: Actualizar) al header de RXN Live para la fácil sanitización de un recargo refrescante sin forzar un "Reset".',
            ],
        ],
        [
            'version' => '1.2.5',
            'build' => '20260406.6',
            'released_at' => '2026-04-06',
            'title' => 'RXN Live: Compatibilidad Nativa de Fechas y Nueva Política de BBDD',
            'summary' => 'Se completó la normalización de inputs temporales para RXN Live delegando el formato visual al Sistema Operativo y la validación en bruto al motor MySQL. Además, se asienta una nueva política inquebrantable de Base de Datos dictada por el usuario.',
            'items' => [
                'Los filtros de fechas avanzados (`Entre`) operan con input type nativo (`date` y `datetime-local`) garantizando compatibilidad cruzada de zonas horarias sin depender del formato regional configurado.',
                'Se implementó regla de estricto cumplimiento para Migraciones de BBDD: a partir de la fecha, todo cambio estructural DDL/DML se hará instantáneo de manera artesanal y la migración PHP quedará como resguardo exclusivo para aplicación en producción vía el panel de Mantenimiento.',
                'Se corrigió y reconfirmó la reparación del "parpadeo imposible" consolidando el History State en la persistencia de vistas de Analytics sin alterar los componentes de navegación backend nativos.',
            ],
        ],
        [
            'version' => '1.2.4',
            'build' => '20260406.5',
            'released_at' => '2026-04-06',
            'title' => 'OTA Fix: Normalización de UI en CRM Notas y Llamadas',
            'summary' => 'Se mejoró la experiencia de usuario inyectando el sistema de Sort interactivo en cabeceras de columnas, reemplazando el listado estático tradicional.',
            'items' => [
                'Se actualizaron los controladores de CrmLlamadas y CrmNotas para soportar ordenamiento de consultas por URL nativa.',
                'Se implementaron enlaces dinámicos en los Theads con feedback direccional.',
            ],
        ],
        [
            'version' => '1.2.3',
            'build' => '20260406.4',
            'released_at' => '2026-04-06',
            'title' => 'Hotfix: Estabilización de Base de Datos para Anura Webhook',
            'summary' => 'Se resolvió un error fatal 500 originado en Plesk al registrar llamadas entrantes, creando las tablas relacionales faltantes para el cruce de clientes.',
            'items' => [
                'Se implementó la migración correctiva que añade la tabla crm_telefonos_clientes para la persistencia retroactiva de llamadas y clientes CRM.',
                'Se inyectó en caliente la columna de cliente_id sobre las llamadas registradas.',
                'El registro en vivo de Anura Webhook queda blindado y preparado para ser subido al servidor.',
            ],
        ],
        [
            'version' => '1.2.2',
            'build' => '20260406.3',
            'released_at' => '2026-04-06',
            'title' => 'Fix: Compatibilidad de Correos y PDS Validation',
            'summary' => 'Se corrigió el desfase visual que presentaban los correos generados por PrintForms al ser recibidos en clientes Microsoft Outlook y se reparó la pérdida de fechas en recargas fallidas del módulo PDS.',
            'items' => [
                'Nuevo template email_render.php dedicado al cuerpo del correo: layout de tabla HTML, sin position:absolute, sin unidades mm, compatible con Outlook 2007 a 2021.',
                'La tipografía configurada en el canvas (fuente, tamaño en pt, color, peso, alineación) se preserva en el email mediante inline styles.',
                'Las imágenes respetan las dimensiones configuradas en el canvas (mm → px a 96 DPI), con límite al ancho del contenedor.',
                'Las tablas/repeaters del canvas se renderizan como HTML table nativo compatible con Outlook.',
                'Los objetos se ordenan por posición vertical (y_mm) para un flujo natural de arriba hacia abajo.',
                'El PDF adjunto y el preview en browser no fueron modificados — siguen funcionando exactamente igual.',
                'Hotfix sobre la tabla: Inyección fuerte de atributos de color para que los clientes en Dark Mode no inviertan a negro un "Papel blanco" predeterminado.',
                'Hotfix PDS: Intercepción del auto-ticker de Javascript de "fecha_inicio" en el formulario de creación. Ahora se bloquea ante un renderizado con errores de validación, previniendo que sobre-escriba incondicionalmente la fecha que el cliente traía en su POST.',
            ],
        ],
        [
            'version' => '1.2.1',
            'build' => '20260405.3',
            'released_at' => '2026-04-05',
            'title' => 'RXN Live: Estabilización de Gráficos y Persistencia de Filtros',
            'summary' => 'Se consolidaron múltiples correcciones sobre el módulo de Analytics RXN_LIVE: renderizado de gráficos consistente en todos los datasets, persistencia de filtros locales al navegar entre informes, y corrección de configuraciones de vistas sistema con campos inválidos.',
            'items' => [
                'El gráfico analítico ahora se renderiza correctamente en Vista Base para todos los datasets (Clientes, Ventas Histórico, Integración Tango) sin requerir guardar una vista.',
                'Los filtros de columna aplicados en un informe se recuperan automáticamente al regresar al mismo dataset después de navegar a otro.',
                'Se corrigió el tipo de gráfico para Clientes (pie → doughnut) ya que "pie" no era una opción válida en el selector, causando que Chart.js recibiera un tipo vacío.',
                'La vista sistema de Ventas Histórico fue corregida con los campos reales del dataset (estado_sincronizacion, cliente_nombre, total).',
                'Se aplicaron límites de seguridad para gráficos tipo dona/pie (máx. 12 segmentos) y para agrupaciones temporales (últimos 20 períodos) evitando renders imperceptibles.',
                'Se unificaron los dos handlers DOMContentLoaded que existían en el mismo archivo, eliminando duplicación de inicialización de pivot slots y eventos de tabs.',
            ],
        ],
        [
            'version' => '1.2.0',
            'build' => '20260405.2',
            'released_at' => '2026-04-05',
            'title' => 'Filtros Avanzados Estilo Excel Globales',
            'summary' => 'Despliegue operativo a lo largo de toda la plataforma de un sistema de filtros potentes con retención de estado, previniendo fuga de contexto y mejorando la agilidad de los operadores en ABMs clave.',
            'items' => [
                'Incorporación de filtros paramétricos directo en los encabezados de columnas (estilo Excel) para Empresas, Usuarios, Artículos, Categorías, Clientes y Pedidos.',
                'El estado de los filtros ahora es persistente, logrando que el operador no pierda la vista de los listados tras entrar al detalle de un renglón y volver hacia atrás.',
                'Motor de SQL centralizado blindado con whitelisting contra inyecciones usando mapeo seguro (AdvancedQueryFilter) soportando alias en sentencias complejas (JOINs).',
            ],
        ],
        [
            'version' => '1.1.58',
            'build' => '20260405.1',
            'released_at' => '2026-04-05',
            'title' => 'Usabilidad Híbrida en Selectores (PDS y Llamadas)',
            'summary' => 'Se rediseñaron los componentes de autocompletado para operar como selectores híbridos, integrando scroll nativo y carga condicional por click.',
            'items' => [
                'Hacer click directo en los selectores despliega un listado de sugerencias óptimo de 50 registros sin obligar a escribir previamente.',
                'Los paneles ahora incluyen un scrollbar visual contenido en la cápsula, compatible con navegación dinámica mediante el ratón y teclado (flechas).',
                'El Backend relajó lógicas restrictivas previas mejorando radicalmente la inmediatez de la interfaz.',
            ],
        ],
        [
            'version' => '1.1.57',
            'build' => '20260404.10',
            'released_at' => '2026-04-04',
            'title' => 'Gestión de Acceso Modular Multi-Tenant',
            'summary' => 'Se implementó una arquitectura de permisos modulares granulares, permitiendo a los administradores habilitar reportes y funciones CRM de forma selectiva por tenant.',
            'items' => [
                'Activación dinámica de "Llamadas CRM", "Monitoreo de Usuarios" y el entorno analítico de "RXN Live" por empresa.',
                'Refactorización de la UI de edición y alta de empresas para sincronizar visualmente la activación de submódulos anidados bajo CRM y Tiendas.',
                'Los entornos operativos (Dashboards) ahora responden proactivamente, inyectando o quitando las tarjetas de acceso correspondientes según los módulos que el tenant tenga habilitados.',
            ],
        ],
        [
            'version' => '1.1.56',
            'build' => '20260404.9',
            'released_at' => '2026-04-04',
            'title' => 'Títulos de Navegador Dinámicos y Rebranding',
            'summary' => 'Se rediseñó el control de marcas y leyendas del sistema, purificando a lo largo del código duro la mención "RXN Tiendas IA" dando un paso más hacia el dinamismo Multi-Tenant.',
            'items' => [
                'Cada administrador master puede definir un "Título de Pestaña de Navegador" diferente para cada inquilino o tenant operativo configurado dentro de RXN Suite.',
                'El framework general (Backoffice y CRM) asume el nombre de fallback global a RXN Suite en lugar del desactualizado "Tiendas IA".',
            ],
        ],
        [
            'version' => '1.1.55',
            'build' => '20260404.8',
            'released_at' => '2026-04-04',
            'title' => 'Usabilidad Híbrida en Selectores (PDS y Llamadas)',
            'summary' => 'Se rediseñaron los componentes de autocompletado en Pedidos de Servicio y Vinculaciones de Central Telefónica para operar como selectores híbridos, integrando scroll nativo y carga condicional por click.',
            'items' => [
                'Hacer click directo en los selectores despliega un listado de sugerencias óptimo de 50 registros sin obligar a escribir previamente.',
                'Los paneles ahora incluyen un scrollbar visual contenido en la cápsula, compatible con navegación dinámica mediante el ratón y teclado (flechas).',
                'El Backend relajó lógicas opresivas de validación previa mejorando radicalmente la presteza en PDS para Artículos, Clientes y Clasificaciones.',
            ],
        ],
        [
            'version' => '1.1.54',
            'build' => '20260404.7',
            'released_at' => '2026-04-04',
            'title' => 'Hotfix: Estabilización de Exportación a Excel en Analytics',
            'summary' => 'Se introdujeron dos correcciones técnicas profundas para garantizar la generación inquebrantable de archivos nativos de Microsoft Excel en el Módulo de Reportes avanzados.',
            'items' => [
                'Se resolvió una incompatibilidad de variables con la librería interna de generación, evitando que descargas presenten mensajes de "archivo corrompido" generados por la suite de Office.',
                'Se mitigó una condición de carrera ("Race-Condition") en navegadores Chrome que omitía enviar los criterios de búsqueda al servidor cuando el operador exportaba a toda velocidad.',
            ],
        ],
        [
            'version' => '1.1.53',
            'build' => '20260404.6',
            'released_at' => '2026-04-04',
            'title' => 'Directorio Expandido: Vinculación Llamadas a Clientes Tango',
            'summary' => 'Se implementó un directorio activo en el CRM permitiendo que el historial y los webhooks reconozcan los perfiles de clientes Tango a través del CallerID (Número de Teléfono).',
            'items' => [
                'La vista de Historial permite acoplar un registro de recepción o salida telefónica con un cliente indexado en Tango Connect.',
                'Esta operación introduce el teléfono en una persistencia local. Futuras llamadas provenientes del mismo son pareadas de forma automática.',
                'La generación en caliente de un Pedido de Servicio hereda el cliente preanexado para reducir los clics operativos a la mitad.',
            ],
        ],
        [
            'version' => '1.1.52',
            'build' => '20260404.5',
            'released_at' => '2026-04-04',
            'title' => 'Fix: Indicador de Estado en Monitoreo CRM',
            'summary' => 'Se corrigió una confusión visual en el tablero de Monitoreo de Operadores del CRM donde todos los usuarios habilitados figuraban como "En línea".',
            'items' => [
                'El punto verde de "Conectado" ahora es exclusivo del usuario que actualmente está navegando la sesión operativa interna.',
                'Los demás usuarios preservan un identificador gris neutro diferenciando visualmente qué cuenta está suspendida de la que se encuentra inactiva.',
            ],
        ],
        [
            'version' => '1.1.51',
            'build' => '20260404.4',
            'released_at' => '2026-04-04',
            'title' => 'Gestión de Favicon en Entorno CRM',
            'summary' => 'Se unifican las capacidades visuales del CRM permitiendo administrar el Favicon de la empresa directamente desde este entorno sin depender de la Tienda pública.',
            'items' => [
                'La vista de Configuración del CRM ahora incluye el campo para la gestión independiente del ícono de la pestaña del navegador (Favicon).',
                'El Favicon permanece atado a la entidad de la Empresa, mostrándose uniformemente tanto en el panel operativo del CRM como en la vidriera de la Tienda.',
            ],
        ],
        [
            'version' => '1.1.50',
            'build' => '20260404.3',
            'released_at' => '2026-04-04',
            'title' => 'Ampliacion Datos en Vista Live PDS',
            'summary' => 'Se amplió el conjunto de datos disponible en la vista en vivo de Pedidos de Servicio (Tiempos), incorporando identificadores directos requeridos por la operativa.',
            'items' => [
                'Se agregó el Código de Artículo (Tango) para facilitar la vinculación de elementos de facturación.',
                'Se expone explícitamente el Nro. Pedido de Tango dentro del selector de columnas del Pivot.',
                'Se estandarizó la nomenclatura visual del autor ("Usuario" en vez de "Técnico") para hacer match con el entorno ABM original.',
            ],
        ],
        [
            'version' => '1.1.49',
            'build' => '20260404.2',
            'released_at' => '2026-04-04',
            'title' => 'Favicon en Entorno CRM / Backoffice',
            'summary' => 'Se unifica el ícono de navegador para que los administradores y operadores logueados en el backoffice vean el mismo favicon configurado para la tienda B2C.',
            'items' => [
                'La cabecera del panel de administración (CRM / Backoffice) ahora toma el favicon de la empresa activa y lo inyecta en la pestaña del navegador.',
                'Esta mejora incrementa el contexto visual cuando los operadores trabajan con múltiples pestañas o empresas.',
            ],
        ],
        [
            'version' => '1.1.48',
            'build' => '20260404.1',
            'released_at' => '2026-04-04',
            'title' => 'Módulo Analytics RXN_LIVE y Gestor de Vistas',
            'summary' => 'Se incorporó el ecosistema de visualización de métricas avanzadas (RXN_LIVE) permitiendo armar tableros estadísticos interactivos sobre conjuntos de datos del CRM, Ecommerce y Taller (PDS).',
            'items' => [
                'Nuevas vistas dinámicas SQL precompiladas desde migraciones OTA para reportes más veloces.',
                'Persistencia descentralizada de layout: cada usuario mantiene su propio guardado de posiciones y selecciones de gráficos JSON en la plataforma.',
                'Integración cruzada de Datasets de Pedidos de Servicio (ERP/Tango), Contactos CRM y Pedidos Web con sincronización real.',
            ],
        ],
        [
            'version' => '1.1.47',
            'build' => '20260403.5',
            'released_at' => '2026-04-03',
            'title' => 'Monitoreo de Usuarios en CRM',
            'summary' => 'Se implementó un nuevo panel dedicado para supervisar y consultar rápidamente al equipo operativo y de ventas en el entorno CRM.',
            'items' => [
                'Nuevo acceso a "Monitoreo de Usuarios" centralizado en la cabecera del CRM.',
                'Visualización directa de operadores, con detalle de su Interno Anura y Perfil comercial de Tango.',
                'Buscador instantáneo optimizado (atajo F3 o "/") sin realizar consultas al servidor.',
            ],
        ],
        [
            'version' => '1.1.46',
            'build' => '20260403.4',
            'released_at' => '2026-04-03',
            'title' => 'Hotfix: Compatibilidad DDL en Migraciones OTA',
            'summary' => 'Se resolvió un falso reporte de error ("There is no active transaction") que aparecía al aplicar actualizaciones estructurales de base de datos desde la Central de Operaciones.',
            'items' => [
                'El motor de actualizaciones (OTA) ahora comprende la mecánica de auto-commit de MySQL al crear tablas.',
                'Las actualizaciones que agregan nuevos módulos ya no quedarán frenadas reportando fallo falso tras aplicar la estructura principal.',
            ],
        ],
        [
            'version' => '1.1.45',
            'build' => '20260403.3',
            'released_at' => '2026-04-03',
            'title' => 'Export/Import de Canvas PrintForms',
            'summary' => 'El editor de Canvas PrintForms permite ahora exportar el diseño completo a un archivo .json portable (con imagen de fondo embebida en base64) e importarlo en cualquier otro entorno con un clic.',
            'items' => [
                'Botón "Exportar" en la toolbar del canvas: descarga un archivo .canvas.json con el diseño completo.',
                'La imagen de fondo se embebe automáticamente en base64 para portabilidad entre entornos.',
                'Botón "Importar" en la toolbar: restaura objetos, page config y fondo; prepara la imagen para subirse en el próximo "Guardar versión".',
                'El estado importado es reversible con Ctrl+Z antes de guardar.',
            ],
        ],
        [
            'version' => '1.1.44',
            'build' => '20260403.2',
            'released_at' => '2026-04-03',
            'title' => 'Fix PrintForms: Color y transparencia en correos',
            'summary' => 'Se corrigió el pipeline de renderizado de emails para que el color de fondo y la opción "Papel sin fondo" configurados en el editor Canvas se apliquen correctamente en los correos enviados.',
            'items' => [
                'El motor PrintFormRenderer ahora propaga background_color y transparent_bg al template de renderizado.',
                'La opción "Papel sin fondo (Transparente)" ahora se respeta en los correos generados.',
                'Se eliminó el !important del CSS del template que anulaba el color inline configurado.',
                'La lógica de color es unificada para email y preview: transparente si así fue configurado, color elegido si no.',
            ],
        ],
        [
            'version' => '1.1.43',
            'build' => '20260403.1',

            'released_at' => '2026-04-03',
            'title' => 'Instalación Unificada OTA (Código + BD)',
            'summary' => 'Se unificó el actualizador del sistema permitiendo subir un ZIP que aplica tanto archivos del núcleo como migraciones de Base de Datos en un solo paso.',
            'items' => [
                'El módulo de Mantenimiento permite ahora resolver las Releases con un solo clic procesando archivos y consultas SQL.',
                'Switch visual para activar o desactivar la auto-aplicación de migraciones incluidas en el ZIP.',
                'El empaquetador del sistema (ReleaseBuilder) ahora incluye correctamente el esquema estructural de Base de Datos.',
            ],
        ],
        [
            'version' => '1.1.42',
            'build' => '20260402.2',
            'released_at' => '2026-04-02',
            'title' => 'Exportación a Excel en Notas CRM',
            'summary' => 'Se incorporó una nueva herramienta para descargar el listado completo de notas operativas actuales al formato Excel (.xlsx) respetando los filtros visuales.',
            'items' => [
                'Botón dedicado "Exportar a Excel" en la vista principal del CRM Notas.',
                'El exportador refleja el tablero actual: aplica los mismos filtros de búsqueda, estado y orden visualizado al momento de la descarga.',
                'Generación instantánea empleando OpenSpout sin afectar el rendimiento del servidor.',
            ],
        ],
        [
            'version' => '1.1.41',
            'build' => '20260402.1',
            'released_at' => '2026-04-02',
            'title' => 'Gestión de Empresas con Switch de Contexto Operativo',
            'summary' => 'Se implementó la separación entre la edición de metadatos globales (ABM empresa) y la navegación operativa profunda dentro de otros Tenants.',
            'items' => [
                'La visualización de Gestión de Empresas permite ahora saltar e "Ingresar" directamente en la sesión operativa de otra empresa manteniéndose como admin.',
                'Se resolvieron fallos de UX por retención de sesión de Tenant 1 ("suite reaxion") al intentar ver el panel interno de terceros sin cambiar explícitamente el ancla operativa (`empresa_id`).',
            ],
        ],
        [
            'version' => '1.1.40',
            'build' => '20260401.2',
            'released_at' => '2026-04-01',
            'title' => 'Integración de Telefonía Anura con Generación de PDS',
            'summary' => 'Se implementó la recepción de webhooks de la central telefónica Anura para visualizar el historial de llamadas en el CRM. Además, se permite derivar llamadas atendidas y finalizadas (HANGUP) directamente a Pedidos de Servicio (PDS), enlazando la duración y horarios automáticamente.',
            'items' => [
                'Nuevo módulo Historial de Llamadas con filtro, papelera y ordenamiento por fecha o duración de llamada.',
                'Botón "Generar PDS" en llamadas válidas que auto-completa el diagnóstico del PDS asimilando al llamante y horarios exactos de sonado/corte.',
                'Validación de seguridad operativa que impide derivar llamadas desde internos de telefonía que no coincidan con la configuración del perfil del usuario.',
                'PDS recibe correctamente la fecha de inicio de la llamada y calcula el momento de finalización a partir de la métrica provista por la central.',
            ],
        ],
        [
            'version' => '1.1.39',
            'build' => '20260401.1',
            'released_at' => '2026-04-01',
            'title' => 'Estandarización Visual Global (Dark/Light Mode Ready)',
            'summary' => 'Se implementó una arquitectura visual robusta mediante Tokens CSS, estandarizando componentes (cards, tablas, formularios) y purgando el esquema Bootstrap legado para garantizar transiciones transparentes entre modos Claro y Oscuro en todo el sistema.',
            'items' => [
                'Expansión extensa de CSS Variables en rxn-theming.css gobernando fondos, contrastes de texto y bordes operacionales.',
                'Refactorización profunda sobre más de 15 módulos ABM quitando clases inflexibles (bg-white, text-dark) que rompían la legibilidad.',
                'Los inputs, textareas y selectores ahora asumen por defecto los fondos del motor visual para no brillar o cegar al operador en entornos oscuros.',
            ],
        ],
        [
            'version' => '1.1.38',
            'build' => '20260331.2',
            'released_at' => '2026-03-31',
            'title' => 'Restauración de Esquemas, Optimizaciones de Búsqueda y JSON Snapshots',
            'summary' => 'Se restauraron y fortalecieron integraciones perdidas: snapshots JSON de perfiles de Tango, lógica robusta de F10 en PDS, y optimizaciones de ranking en buscadores de catálogos y clientes CRM.',
            'items' => [
                'El esquema de usuarios suma resiliencia al migrar en runtime JSON snapshots faltantes de Tango Connect.',
                'Renombre del campo `falla` a `motivo_descuento` a lo largo de PDS y los reportes en Canvas Impresión.',
                'El buscador de Clientes y Artículos CRM implementa ranking por peso (Match exacto > Prefix match > Fulltext).',
                'El formulario PDS diferencia con confirmación el envío a ERP vs un guardado en borrador simple validando fecha finalizado.',
            ],
        ],
        [
            'version' => '1.1.37',
            'build' => '20260331.1',
            'released_at' => '2026-03-31',
            'title' => 'Gestión de Notas y Aislamiento de Módulos (Tenants)',
            'summary' => 'Se implementó el nuevo módulo universal de Notas CRM (con sistema propio de autocompletado de Clientes y Etiquetas), y se estabilizó un aspecto crítico de la arquitectura: el aislamiento total de sesión al cambiar de empresa.',
            'items' => [
                'Nuevo módulo "Notas CRM" con vista Read-Only diferenciada del formulario de edición, y acciones estándar (Copiar, Eliminar, Tabla con Ordenamiento).',
                'El framework CRM consolida la regla de oro Rxn: Todo panel debe permitir búsqueda asíncrona (AJAX en Vainilla JS) sin fallar el UI.',
                'Aislamiento Multi-Tenancy resuelto: editar el perfil del usuario ahora inyecta en caliente el cambio de empresa_id a la Sesión PHP, evitando fugas de información entre entornos.',
            ],
        ],
        [
            'version' => '1.1.36',
            'build' => '20260330.14',
            'released_at' => '2026-03-30',
            'title' => 'Envío Automatizado de Documentos (Mail + PDF)',
            'summary' => 'CRM ahora despacha Presupuestos y Pedidos de Servicio automáticamente mediante la configuración SMTP de la empresa, procesando on-the-fly el PDF adjunto y el cuerpo del correo desde las plantillas Canvas predefinidas.',
            'items' => [
                'Se implementó el servicio transversal DocumentMailerService orquestando MailService, PrintForms y DomPDF.',
                'Configuración Empresa suma parametrización visual explícita para designar la plantilla del cuerpo HTML y del PDF adjunto para Presupuestos y PDS.',
                'Los operadores pueden despachar un documento editable usando el botón "Enviar por mail" directamente desde la barra comercial sin abandonar el flujo.',
            ],
        ],
        [
            'version' => '1.1.35',
            'build' => '20260330.13',
            'released_at' => '2026-03-30',
            'title' => 'Hotfix: Resolución de Rutas ApiClient en Tango Connect',
            'summary' => 'Se unificó el manejo de URLs base y sufijos de endpoints a través de todos los clientes de integración Tango resguardando la conexión a la base y resolviendo un error de consulta vacía silenciosa al buscar clasificaciones PDS.',
            'items' => [
                'TangoApiClient ahora pre-procesa urls base removiendo sufijos espurios como /Api o /Api/Get introducidos desde el UI.',
                'Endpoints de lectura (Get, GetById) fueron migrados a sintaxis explícita con prefijo /Api/ para resolver colisiones de ruteo.',
                'Refactorización limpia elimina el fallo silencioso 200 OK con payload vacío en el proceso 326.',
            ],
        ],
        [
            'version' => '1.1.34',
            'build' => '20260330.12',
            'released_at' => '2026-03-30',
            'title' => 'Integración en Vivo de Clasificaciones PDS',
            'summary' => 'Se depreca el catálogo local manual estático de clasificaciones operativas remplazando el motor por una consulta en vivo interactuando bidireccionalmente contra Tango Connect usando el Process 326.',
            'items' => [
                'TangoApiClient agrega getClasificacionesPds extrayendo código visible e ID_GVA81 subyacente.',
                'PedidoServicioRepository recibe un update model layer para sostener clasificacion_id_tango de cara al futuro.',
                'El script rxn-ui del autocomplete extrae atributos ocultos silenciosos mapeando items complejos.',
                'El Payload Engine inserta un mapping directo de base para priorizar selectores seguros sobre strings crudos al remitir el PDS.',
            ],
        ],
        [
            'version' => '1.1.33',
            'build' => '20260330.11',
            'released_at' => '2026-03-30',
            'title' => 'Canvas de impresion para Pedidos de Servicio',
            'summary' => 'El modulo PDS suma la mecanica de impresion canvas ya existente en Presupuestos, con su propio contexto de variables incluyendo tiempos, diagnostico y clasificacion.',
            'items' => [
                'Se crea PedidoServicioPrintContextBuilder con grupos empresa, cliente, articulo, pedido y tiempos.',
                'PedidoServicioController incorpora printPreview siguiendo el mismo flujo que Presupuestos.',
                'PrintFormRegistry registra el documento crm_pds con objetos predeterminados listos para operar.',
                'El formulario de edicion PDS suma los botones Imprimir y Formulario en la barra de acciones.',
            ],
        ],
        [
            'version' => '1.1.32',
            'build' => '20260329.10',
            'released_at' => '2026-03-29',
            'title' => 'Cache local del perfil Tango en Configuración',
            'summary' => 'Al guardar Configuracion se sincroniza y persiste el detalle completo del perfil para usarlo en pedidos sin reconsultar a Connect.',
            'items' => [
                'empresa_config y empresa_config_crm almacenan los IDs claves, flag de moneda y snapshot JSON del perfil.',
                'El guardado de Configuración llama a Tango una sola vez y deja la fecha de sincronización visible en la UI.',
                'TangoOrderHeaderResolver consume el snapshot antes de volver a consultar y registra fallback solo si está ausente.',
            ],
        ],
        [
            'version' => '1.1.31',
            'build' => '20260329.9',
            'released_at' => '2026-03-29',
            'title' => 'Override de moneda local para company 351',
            'summary' => 'Mientras Axoft no libere el catálogo oficial de monedas, los pedidos hacia company 351 fuerzan ID_MONEDA = 2 para que Pesos no sea rechazado.',
            'items' => [
                'Se agregó un override por `tango_connect_company_id` en el resolver: company 351 ahora envía 2 como moneda local.',
                'El resto de los tenants siguen usando la heurística `MONEDA_HABITUAL`/fallback.',
                'Documentado en logs/estado como medida temporal hasta consumir el maestro real.',
            ],
        ],
        [
            'version' => '1.1.30',
            'build' => '20260329.8',
            'released_at' => '2026-03-29',
            'title' => 'Resolver forzado a usar la URL Posta de Connect',
            'summary' => 'El resolver de cabecera corrige la URL base de Axoft (agregando /Api o usando la llave) para poder bajar el detalle del perfil y evitar talonarios/monedas en fallback.',
            'items' => [
                'Si el operador guardó `https://000357-014.connect.axoft.com` sin `/Api`, el resolver lo normaliza antes de llamar a `GetById`.',
                'Con esto, `ID_GVA43_TALON_PED` vuelve a salir del perfil real y no del legacy 6 en empresas que usan company 351.',
                'La heurística de moneda (`C => 1 / resto => 0`) ahora se evalúa con datos reales del perfil porque la consulta ya no devuelve nulo.',
            ],
        ],
        [
            'version' => '1.1.29',
            'build' => '20260329.7',
            'released_at' => '2026-03-29',
            'title' => 'Heuristica temporal de moneda por perfil Tango',
            'summary' => 'PDS y pedidos web ya leen `MONEDA_HABITUAL` del perfil para decidir `ID_MONEDA`, aplicando la regla local vs extranjera documentada mientras esperamos el catalogo oficial.',
            'items' => [
                'TangoOrderHeaderResolver mapea `MONEDA_HABITUAL = C` a `ID_MONEDA = 1` (pesos) y cualquier otro flag a `ID_MONEDA = 0`, dejando fallback legacy solo si el perfil no expone dato.',
                'TangoOrderMapper acepta valores cero para `ID_MONEDA`, evitando que el normalizador legacy descarte la moneda extranjera.',
                'Se deja registrada la heuristica bimonetaria en docs para revisar cuando Tengamos el endpoint real de monedas (process 16660 o equivalente).',
            ],
        ],
        [
            'version' => '1.1.28',
            'build' => '20260329.6',
            'released_at' => '2026-03-29',
            'title' => 'Hotfix del perfil Tango y resolver inicial de pedidos',
            'summary' => 'Configuracion vuelve a cargar perfiles habilitados reales desde Tango y los pedidos de Tiendas/CRM empiezan a resolver su cabecera comercial a partir del perfil seleccionado.',
            'items' => [
                'El selector `Perfil de pedido Tango` corrige la carga/search sobre `process=20020` usando `view=Habilitados` y los campos reales del catalogo.',
                'Pedidos Web y Pedidos de Servicio CRM usan un resolver compartido para poblar `ID_PERFIL_PEDIDO`, talonario y demas IDs de cabecera desde el detalle del perfil.',
                'Se mantienen fallbacks legacy acotados para talonario, deposito y moneda mientras se completa la migracion del resto de consumidores.',
            ],
        ],
        [
            'version' => '1.1.27',
            'build' => '20260329.5',
            'released_at' => '2026-03-29',
            'title' => 'Configuracion unifica Perfil de pedido Tango',
            'summary' => 'Tiendas y CRM dejan de exponer listas, deposito y talonario en Configuracion, usando un unico selector de perfil de pedido alimentado por Tango Connect `process=20020`.',
            'items' => [
                'EmpresaConfig suma el selector compartido `Perfil de pedido Tango` con persistencia por area y snapshot local de codigo/descripcion.',
                'La recarga de metadata por empresa Connect ya no consulta listas/deposito en este flujo y consume solo empresas + perfiles de pedido.',
                'Se preservan los campos legacy en base para no romper consumidores existentes mientras se planifica la migracion de payloads.',
            ],
        ],
        [
            'version' => '1.1.26',
            'build' => '20260329.4',
            'released_at' => '2026-03-29',
            'title' => 'Formularios imprimibles con tablas repetitivas',
            'summary' => 'El motor de impresion suma soporte para bloques repetitivos (items), completando la primera version operativa del documento de presupuesto.',
            'items' => [
                'El canvas editor ahora soporta el objeto `table_repeater` para iterar renglones de documentos.',
                'Las tablas son visualmente ajustables y persisten sus columnas, anchos y estilos en JSON.',
                'Presupuestos CRM inaugura el circuito de impresion con un boton "Imprimir" que abre la version renderizada lista para el navegador.',
                'El contexto de impresion se aplanó y estandarizó para facilitar el diseño del documento.',
            ],
        ],
        [
            'version' => '1.1.25',
            'build' => '20260329.3',
            'released_at' => '2026-03-29',
            'title' => 'Correccion en PDS por widget de bitacora',
            'summary' => 'Se resolvio un error interno que impedia abrir el formulario de Pedidos de Servicio cuando el modulo tenia notas con imagenes adjuntas registradas por administradores.',
            'items' => [
                'Se aislaron las variables internas del widget de bitacora compartida para evitar colisiones con las pantallas operativas.',
                'El formulario de Pedidos de Servicio vuelve a renderizar correctamente en todos los casos sin importar el historial de notas.',
            ],
        ],
        [
            'version' => '1.1.24',
            'build' => '20260329.2',
            'released_at' => '2026-03-29',
            'title' => 'PDS corrige fecha actual y suma borrado de capturas',
            'summary' => 'Pedidos de Servicio estabiliza la funcionalidad del reloj en tiempo real para las fechas y permite eliminar imagenes que ya estaban guardadas.',
            'items' => [
                'El checkbox de ahora funciona correctamente tanto en Inicio como en Finalizado actualizando los inputs.',
                'Se agrega el boton para eliminar las capturas que ya estaban subidas a disco y limpiar el PDS.',
            ],
        ],
        [
            'version' => '1.1.23',
            'build' => '20260329.1',
            'released_at' => '2026-03-29',
            'title' => 'Sincronizacion tolerante a multiples sucursales',
            'summary' => 'La sincronizacion de clientes CRM desde Tango ahora soporta multiples clientes o sucursales que comparten el mismo correo electronico bajo una sola empresa.',
            'items' => [
                'Se elimino la restriccion estricta que impedia tener correos electronicos duplicados para clientes de una misma empresa.',
                'El proceso de sincronizacion ya no aborta al recibir multiples sucursales con el mismo email comercial.',
                'La actualizacion repara automaticamente la base de datos local en las instalaciones existentes.',
            ],
        ],
        [
            'version' => '1.1.22',
            'build' => '20260328.24',
            'released_at' => '2026-03-28',
            'title' => 'Canvas de impresion base y editor visual A4',
            'summary' => 'La plataforma suma la base persistente de formularios de impresion y un primer editor visual A4 para Presupuesto CRM, con fondo, fuentes, objetos posicionados y versionado.',
            'items' => [
                'Se agrega el modulo Formularios de Impresion dentro del CRM con listado y editor visual propio.',
                'El canvas editable soporta fondo, texto fijo, variables, lineas, rectangulos y fuentes desde una whitelist controlada.',
                'Las definiciones se guardan como versiones persistentes con assets y JSON estructurado, en lugar de HTML suelto.',
                'Presupuesto CRM ya puede enlazarse con una mecanica documental estandar de la plataforma sin depender de CrystalReports.',
            ],
        ],
        [
            'version' => '1.1.21',
            'build' => '20260328.23',
            'released_at' => '2026-03-28',
            'title' => 'PDS libera mejor el diagnostico y suma hora actual',
            'summary' => 'Pedidos de Servicio baja el bloque de pegado de imagenes debajo del diagnostico, achica miniaturas y agrega un check para capturar la hora actual al finalizar.',
            'items' => [
                'El bloque de pegado de imagenes deja de quedar arriba del diagnostico.',
                'Las miniaturas del diagnostico se compactan un poco mas.',
                'Finalizado puede tomar la fecha y hora actual con un checkbox sin tipear manualmente.',
            ],
        ],
        [
            'version' => '1.1.20',
            'build' => '20260328.22',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion afina Connect y sus catalogos',
            'summary' => 'Configuracion restaura bien el estado visual del boton Connect y extiende la busqueda asistida a listas y deposito para acelerar la seleccion operativa.',
            'items' => [
                'El boton de metadata ya no queda trabado en Resolviendo descripciones tras cambiar de empresa.',
                'Lista 1, Lista 2 y Deposito suman buscadores con sugerencias locales sobre la metadata cargada.',
                'Tiendas y CRM reciben el mismo ajuste al compartir la pantalla de Configuracion.',
            ],
        ],
        [
            'version' => '1.1.19',
            'build' => '20260328.21',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion reengancha bien los catalogos Connect',
            'summary' => 'Configuracion vuelve a enviar el formulario correcto en sus llamadas AJAX, por lo que la empresa Connect seleccionada alimenta otra vez la carga de listas y deposito.',
            'items' => [
                'El JS de Configuracion ahora serializa explicitamente `#empresa-config-form`.',
                'La empresa Connect elegida vuelve a viajar en la recarga de metadata y destraba listas/deposito.',
                'El ajuste impacta tanto en Tiendas como en CRM al compartir la misma pantalla.',
            ],
        ],
        [
            'version' => '1.1.18',
            'build' => '20260328.20',
            'released_at' => '2026-03-28',
            'title' => 'PDS ordena mejor sus previews de diagnostico',
            'summary' => 'Pedidos de Servicio mueve el preview temporal de capturas debajo del diagnostico, reduce el tamaño de miniaturas y evita duplicar numeracion por etiquetas viejas.',
            'items' => [
                'El preview de imagenes pegadas deja de aparecer en la caja superior y pasa debajo del textarea Diagnostico.',
                'Las miniaturas del diagnostico se achican para ocupar menos espacio operativo.',
                'El siguiente #imagenN ahora contempla etiquetas historicas con o sin numeral para no repetir numeracion.',
            ],
        ],
        [
            'version' => '1.1.17',
            'build' => '20260328.19',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion afina el buscador de empresa Connect',
            'summary' => 'El buscador de empresa Connect gana una presentacion mas clara con icono, placeholder guiado y feedback visible de la empresa seleccionada.',
            'items' => [
                'La entrada visible de empresa Connect queda mas alineada con el patron de busqueda del resto del sistema.',
                'Una pill de estado muestra si hay empresa elegida y cual quedo activa.',
                'El flujo operativo sigue siendo el mismo para Tiendas y CRM porque ambos comparten la pantalla de Configuracion.',
            ],
        ],
        [
            'version' => '1.1.16',
            'build' => '20260328.18',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion mejora empresa Connect y catalogos',
            'summary' => 'Configuracion ya no consulta listas y depositos sin empresa valida, y el selector de empresa Connect suma busqueda con sugerencias para agilizar la eleccion.',
            'items' => [
                'La validacion inicial de Connect trae el maestro de empresas y deja los catalogos dependientes para cuando haya una empresa seleccionada.',
                'Elegir una empresa desde el buscador visible dispara la carga correcta de listas de precio y deposito.',
                'El ajuste aplica a Tiendas y CRM porque ambos comparten la misma pantalla de configuracion.',
            ],
        ],
        [
            'version' => '1.1.15',
            'build' => '20260328.17',
            'released_at' => '2026-03-28',
            'title' => 'PDS compacta su bloque tecnico',
            'summary' => 'Pedidos de Servicio reubica su fila operativa dentro del detalle tecnico y hace que las miniaturas del diagnostico ocupen menos espacio visual.',
            'items' => [
                'Solicito, Pedido Tango y Articulo bajan al bloque tecnico para liberar la parte alta del formulario.',
                'Las miniaturas del diagnostico ya no dejan una franja ancha inutil cuando hay pocas imagenes.',
                'Se sostiene la experiencia compacta del PDS sin meter dependencias nuevas.',
            ],
        ],
        [
            'version' => '1.1.14',
            'build' => '20260328.16',
            'released_at' => '2026-03-28',
            'title' => 'Configuracion alinea selectores con empresa Connect',
            'summary' => 'Tiendas y CRM ahora recargan listas y deposito al cambiar la empresa Connect, evitando guardar combinaciones comerciales inconsistentes.',
            'items' => [
                'Cambiar la empresa Connect recompone en cascada Lista 1, Lista 2 y Deposito dentro de Configuracion.',
                'El backend rechaza guardados si la empresa cambio pero los selectores dependientes quedaron sin refrescar.',
                'La correccion aplica tanto a Tiendas como a CRM porque ambos comparten el modulo EmpresaConfig.',
            ],
        ],
        [
            'version' => '1.1.13',
            'build' => '20260328.15',
            'released_at' => '2026-03-28',
            'title' => 'Presupuestos CRM con pantalla operativa usable',
            'summary' => 'CRM suma una primera pantalla util de presupuestos con cabecera comercial, autocompletado por cliente, renglones acumulables y base local preparada para crecer hacia impresion y versionado.',
            'items' => [
                'Se agrega el modulo Presupuestos CRM con listado, alta y edicion propias dentro del dashboard CRM.',
                'La cabecera comercial se autocompleta desde clientes CRM y catalogos cacheados localmente por empresa.',
                'El detalle se arma por renglones editables buscando articulos CRM por codigo o descripcion.',
                'Cabecera, items y totales quedan persistidos como snapshots locales para no romper historicos.',
            ],
        ],
        [
            'version' => '1.1.12',
            'build' => '20260328.14',
            'released_at' => '2026-03-28',
            'title' => 'PDS toma clasificaciones desde Configuracion CRM',
            'summary' => 'Configuracion CRM suma un catalogo local de clasificaciones y el selector del PDS pasa a consumirlo sin depender de un endpoint externo.',
            'items' => [
                'Configuracion CRM incorpora un textarea para pegar clasificaciones operativas del PDS.',
                'El selector Clasificacion del PDS busca por codigo o descripcion sobre ese catalogo interno.',
                'Los PDS guardan snapshot de codigo y descripcion de clasificacion para preservar historico.',
            ],
        ],
        [
            'version' => '1.1.10',
            'build' => '20260328.12',
            'released_at' => '2026-03-28',
            'title' => 'PDS valida mejor las respuestas de Tango',
            'summary' => 'Pedidos de Servicio estabiliza sus rutas de Connect, detecta rechazos semanticos aunque el HTTP sea 200 y deja trazabilidad mas fiel del estado real del envio.',
            'items' => [
                'TangoOrderClient alinea rutas `/Api/Create` y `/Api/GetByFilter` con el resto del stack.',
                'El envio PDS ya no toma como exitoso un `succeeded=false` de Connect.',
                'La prueba real del PDS confirmó que `ID_STA11` ya se resuelve y que el bloqueo actual está en la configuración comercial del artículo dentro de Tango.',
            ],
        ],
        [
            'version' => '1.1.9',
            'build' => '20260328.11',
            'released_at' => '2026-03-28',
            'title' => 'PDS con monitor de tiempo mas presente',
            'summary' => 'Pedidos de Servicio compacta mas su layout tecnico y deja el monitor de tiempos mucho mas visible mientras se carga el trabajo.',
            'items' => [
                'Se reducen espacios entre inputs y la altura visible de Diagnostico/Falla.',
                'El bloque de tiempos queda mas cerca del detalle tecnico y se sostiene visible en desktop.',
                'Las miniaturas del diagnostico permanecen debajo del textarea sin romper el seguimiento operativo.',
            ],
        ],
        [
            'version' => '1.1.8',
            'build' => '20260328.10',
            'released_at' => '2026-03-28',
            'title' => 'Store con toggle frontal y ofertas por articulo',
            'summary' => 'La tienda publica ahora alterna entre categorias y catalogo, el detalle vuelve con contexto y cada articulo de Tiendas puede mostrar una oferta comercial usando Lista 2 como precio promocional.',
            'items' => [
                'El Store permite alternar entre vista de categorias y vista de catalogo desde el frente.',
                'El detalle de producto incorpora un boton de vuelta contextual al recorrido previo.',
                'Tiendas suma un switch local por articulo para publicar oferta con badge y precio tachado.',
                'Carrito y checkout respetan el precio promocional cuando la oferta esta activa.',
            ],
        ],
        [
            'version' => '1.1.7',
            'build' => '20260328.9',
            'released_at' => '2026-03-28',
            'title' => 'PDS afina lookup Tango y miniaturas de diagnostico',
            'summary' => 'Pedidos de Servicio mejora la resolucion de ID_STA11 al enviar a Tango y alinea las capturas del diagnostico con la visual compacta de la bitacora.',
            'items' => [
                'El lookup de ID_STA11 ahora tolera variantes del codigo y distintas estructuras de respuesta de Connect.',
                'Las capturas pegadas en Diagnostico se muestran como miniaturas chicas debajo del textarea.',
                'Se sostiene la mecanica local-first del PDS sin depender de busquedas remotas al seleccionar articulo.',
            ],
        ],
        [
            'version' => '1.1.6',
            'build' => '20260328.8',
            'released_at' => '2026-03-28',
            'title' => 'Backoffice con usuario visible y acceso rapido a tienda',
            'summary' => 'El backoffice ahora identifica al usuario activo en cabecera y resuelve un acceso directo a la tienda publica asociada a su empresa cuando existe.',
            'items' => [
                'Las cabeceras principales del backoffice muestran `Hola, {usuario}` para dar contexto inmediato de sesion.',
                'Si la empresa actual tiene Tiendas habilitado, esta activa y posee slug, aparece un boton para abrir su tienda publica.',
                'Cuando no existe una tienda publica valida, el backoffice informa el motivo en lugar de exponer un enlace inconsistente.',
            ],
        ],
        [
            'version' => '1.1.5',
            'build' => '20260328.7',
            'released_at' => '2026-03-28',
            'title' => 'PDS estable con capturas en diagnostico',
            'summary' => 'Pedidos de Servicio estabiliza su guardado/envio a Tango y suma capturas pegadas en Diagnostico con referencias internas reutilizables.',
            'items' => [
                'Se corrige el fallo de persistencia que rompia el update del PDS al guardar cambios.',
                'Diagnostico admite capturas pegadas desde portapapeles y las referencia como #imagenN.',
                'Los adjuntos del PDS quedan guardados en disco y persistidos en una tabla propia del modulo.',
            ],
        ],
        [
            'version' => '1.1.4',
            'build' => '20260328.6',
            'released_at' => '2026-03-28',
            'title' => 'Clientes CRM cacheados desde Tango',
            'summary' => 'Clientes CRM deja de reutilizar el ABM manual de Tiendas y pasa a operar con una cache local sincronizable desde Tango/Connect, alineada al patron de Articulos CRM.',
            'items' => [
                'Clientes CRM ahora lista, busca, pagina y edita sobre `crm_clientes` como cache local propia del entorno.',
                'Se agrega `Sync Clientes` desde CRM para persistir y actualizar clientes Tango/Connect (process 2117).',
                'Pedidos de Servicio consume la nueva tabla local de clientes CRM sincronizados para sugerencias y envio a Tango.',
            ],
        ],
        [
            'version' => '1.1.3',
            'build' => '20260328.5',
            'released_at' => '2026-03-28',
            'title' => 'Clientes CRM independientes',
            'summary' => 'CRM suma su propia base de clientes independiente, con la misma experiencia de validacion y persistencia validada en Tiendas.',
            'items' => [
                'Se implementó Clientes CRM en entorno independiente, replicando la UX de resolucion de Tango.',
                'Pedidos de Servicio ahora asocia y sugiere clientes usando la base local propia del CRM.',
                'Aislamiento completo de relaciones comerciales de clientes entre ambos entornos operativos.',
            ],
        ],
        [
            'version' => '1.1.2',
            'build' => '20260328.4',
            'released_at' => '2026-03-28',
            'title' => 'Bitacora en dock minimizado y recuperacion mas rapida',
            'summary' => 'La bitacora deja de colapsar como tarjeta grande y pasa a un dock chico abajo a la derecha, restaurando despues su layout expandido previo.',
            'items' => [
                'El estado minimizado ahora se ve como un dock compacto y no como una ventana deformada.',
                'Al restaurar, la bitacora recupera posicion y tamaño expandido anteriores.',
                'Se suma un launcher minimo para reabrir rapido el panel desde la esquina inferior derecha.',
            ],
        ],
        [
            'version' => '1.1.1',
            'build' => '20260328.3',
            'released_at' => '2026-03-28',
            'title' => 'Bitacora minimizable y refinamiento interno de ergonomia',
            'summary' => 'La bitacora flotante ahora puede minimizarse como una ventana compacta, conservando su tamaño expandido para volver al trabajo sin reacomodarla.',
            'items' => [
                'La bitacora suma un estado minimizado prolijo, mas cercano a una ventana reducida que a un panel deformado.',
                'El layout del widget conserva el tamaño expandido previo y lo restaura al volver a abrirlo.',
                'El header minimizado tambien permite restaurar rapido la bitacora sin romper el flujo del modulo.',
            ],
        ],
        [
            'version' => '1.1.0',
            'build' => '20260328.2',
            'released_at' => '2026-03-28',
            'title' => 'Split operativo Tiendas/CRM con categorias y primer CRM real',
            'summary' => 'La base operativa se expande con categorias comerciales en Store, separacion funcional entre Tiendas y CRM, configuracion CRM propia y el primer modulo operativo del circuito CRM.',
            'items' => [
                'Tiendas incorpora categorias locales con filtro publico y asignacion por SKU persistente.',
                'Launcher y dashboards separan Tiendas y CRM segun flags reales del tenant.',
                'CRM ya cuenta con configuracion operativa propia y servicios preparados por area.',
                'Se suma Pedidos de Servicio como primer modulo operativo real del entorno CRM.',
            ],
        ],
        [
            'version' => '1.0.0',
            'build' => '20260328.1',
            'released_at' => '2026-03-28',
            'title' => 'Base operativa con versionado visible',
            'summary' => 'Se formaliza una fuente unica de version y se publica un bloque de Novedades visible para operadores y clientes.',
            'items' => [
                'Se centralizo la version activa del sistema en una unica configuracion interna.',
                'La tienda publica ahora muestra un bloque Novedades con la release vigente.',
                'Launcher y dashboards exponen la misma version para evitar desalineaciones operativas.',
            ],
        ],
    ],
];
