<?php
declare(strict_types=1);

namespace App\Modules\PrintForms;

class PrintFormRegistry
{
    public static function documentsForArea(string $area): array
    {
        $area = strtolower(trim($area));

        return array_values(array_filter(self::allDocuments(), static function (array $document) use ($area): bool {
            return ($document['area'] ?? '') === $area;
        }));
    }

    public static function document(string $documentKey): ?array
    {
        foreach (self::allDocuments() as $document) {
            if (($document['document_key'] ?? '') === $documentKey) {
                return $document;
            }
        }

        return null;
    }

    public static function availableFonts(): array
    {
        return [
            ['value' => 'Arial, Helvetica, sans-serif', 'label' => 'Arial'],
            ['value' => 'Helvetica, Arial, sans-serif', 'label' => 'Helvetica'],
            ['value' => '"Times New Roman", Times, serif', 'label' => 'Times New Roman'],
            ['value' => 'Georgia, serif', 'label' => 'Georgia'],
            ['value' => '"Courier New", Courier, monospace', 'label' => 'Courier New'],
        ];
    }

    private static function allDocuments(): array
    {
        return [
            [
                'document_key' => 'crm_presupuesto',
                'area' => 'crm',
                'label' => 'Presupuesto CRM',
                'description' => 'Formulario imprimible del presupuesto comercial de CRM, pensado como primera base del futuro circuito documental.',
                'default_page_config' => [
                    'page' => [
                        'size' => 'A4',
                        'orientation' => 'portrait',
                        'width_mm' => 210,
                        'height_mm' => 297,
                        'margin_top_mm' => 0,
                        'margin_right_mm' => 0,
                        'margin_bottom_mm' => 0,
                        'margin_left_mm' => 0,
                    ],
                    'grid' => [
                        'enabled' => true,
                        'step_mm' => 2,
                        'snap' => true,
                    ],
                    'background' => [
                        'asset_id' => null,
                        'opacity' => 1,
                    ],
                    'defaults' => [
                        'font_family' => 'Arial, Helvetica, sans-serif',
                        'font_size_pt' => 10,
                        'color' => '#111111',
                    ],
                ],
                'default_objects' => [
                    [
                        'id' => 'obj_title_text',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 12,
                        'w_mm' => 75,
                        'h_mm' => 8,
                        'z_index' => 10,
                        'content' => 'PRESUPUESTO',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 15,
                            'font_weight' => 700,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_title_number',
                        'type' => 'variable',
                        'x_mm' => 140,
                        'y_mm' => 12,
                        'w_mm' => 58,
                        'h_mm' => 8,
                        'z_index' => 11,
                        'source' => 'presupuesto.numero',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 14,
                            'font_weight' => 700,
                            'color' => '#111111',
                            'align' => 'right',
                        ],
                    ],
                    [
                        'id' => 'obj_fecha_label',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 24,
                        'w_mm' => 25,
                        'h_mm' => 6,
                        'z_index' => 10,
                        'content' => 'Fecha:',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 10,
                            'font_weight' => 700,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_fecha_value',
                        'type' => 'variable',
                        'x_mm' => 35,
                        'y_mm' => 24,
                        'w_mm' => 55,
                        'h_mm' => 6,
                        'z_index' => 10,
                        'source' => 'presupuesto.fecha',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 10,
                            'font_weight' => 400,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_cliente_label',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 34,
                        'w_mm' => 25,
                        'h_mm' => 6,
                        'z_index' => 10,
                        'content' => 'Cliente:',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 10,
                            'font_weight' => 700,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_cliente_value',
                        'type' => 'variable',
                        'x_mm' => 35,
                        'y_mm' => 34,
                        'w_mm' => 130,
                        'h_mm' => 6,
                        'z_index' => 10,
                        'source' => 'cliente.nombre',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 10,
                            'font_weight' => 400,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_separador_top',
                        'type' => 'line',
                        'x_mm' => 10,
                        'y_mm' => 44,
                        'w_mm' => 190,
                        'h_mm' => 0,
                        'z_index' => 5,
                        'style' => [
                            'stroke' => '#1f2937',
                            'stroke_width_mm' => 0.35,
                        ],
                    ],
                    [
                        'id' => 'obj_items_table',
                        'type' => 'table_repeater',
                        'x_mm' => 10,
                        'y_mm' => 52,
                        'w_mm' => 190,
                        'h_mm' => 180,
                        'z_index' => 6,
                        'source' => 'items[]',
                        'show_header' => true,
                        'row_height_mm' => 8,
                        'columns' => [
                            ['key' => 'codigo', 'label' => 'Codigo', 'width_mm' => 26, 'align' => 'left'],
                            ['key' => 'descripcion', 'label' => 'Descripcion', 'width_mm' => 82, 'align' => 'left'],
                            ['key' => 'cantidad', 'label' => 'Cant.', 'width_mm' => 18, 'align' => 'right'],
                            ['key' => 'precio_unitario', 'label' => 'Precio', 'width_mm' => 30, 'align' => 'right'],
                            ['key' => 'bonificacion', 'label' => 'Bonif.', 'width_mm' => 16, 'align' => 'right'],
                            ['key' => 'importe', 'label' => 'Importe', 'width_mm' => 18, 'align' => 'right'],
                        ],
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 9,
                            'color' => '#111111',
                            'header_background' => '#e5e7eb',
                            'header_color' => '#111111',
                            'border_color' => '#94a3b8',
                        ],
                    ],
                    [
                        'id' => 'obj_footer_box',
                        'type' => 'rect',
                        'x_mm' => 10,
                        'y_mm' => 255,
                        'w_mm' => 190,
                        'h_mm' => 28,
                        'z_index' => 2,
                        'style' => [
                            'stroke' => '#94a3b8',
                            'stroke_width_mm' => 0.3,
                            'fill' => 'transparent',
                        ],
                    ],
                ],
                'variables' => [
                    [
                        'group' => 'Empresa',
                        'items' => [
                            ['source' => 'empresa.nombre', 'label' => 'Empresa / Nombre'],
                            ['source' => 'empresa.cuit', 'label' => 'Empresa / CUIT'],
                            ['source' => 'empresa.header_url', 'label' => 'Empresa / Header (Imagen)'],
                            ['source' => 'empresa.footer_url', 'label' => 'Empresa / Footer (Imagen)'],
                        ],
                    ],
                    [
                        'group' => 'Cliente',
                        'items' => [
                            ['source' => 'cliente.nombre', 'label' => 'Cliente / Nombre'],
                            ['source' => 'cliente.documento', 'label' => 'Cliente / Documento'],
                        ],
                    ],
                    [
                        'group' => 'Presupuesto',
                        'items' => [
                            ['source' => 'presupuesto.numero', 'label' => 'Presupuesto / Numero'],
                            ['source' => 'presupuesto.fecha', 'label' => 'Presupuesto / Fecha'],
                            ['source' => 'presupuesto.usuario', 'label' => 'Presupuesto / Usuario (Creador)'],
                        ],
                    ],
                    [
                        'group' => 'Totales',
                        'items' => [
                            ['source' => 'totales.subtotal', 'label' => 'Totales / Subtotal'],
                            ['source' => 'totales.descuento', 'label' => 'Totales / Descuento'],
                            ['source' => 'totales.total', 'label' => 'Totales / Total'],
                        ],
                    ],
                ],
                'repeaters' => [
                    [
                        'source' => 'items[]',
                        'label' => 'Renglones / Items[]',
                        'description' => 'Bloque repetitivo para detalle comercial del presupuesto.',
                    ],
                ],
                'sample_context' => [
                    'empresa' => [
                        'nombre'     => 'RXN Demo',
                        'cuit'       => '30-12345678-9',
                        'header_url' => 'https://placehold.co/800x200?text=Header+Logo',
                        'footer_url' => 'https://placehold.co/800x100?text=Footer+Logo',
                    ],
                    'cliente' => [
                        'nombre' => 'Cliente Demo S.A.',
                        'documento' => '20-30111222-3',
                    ],
                    'presupuesto' => [
                        'numero' => '000123',
                        'fecha' => '28/03/2026',
                    ],
                    'totales' => [
                        'subtotal' => '$ 120.000,00',
                        'descuento' => '$ 5.000,00',
                        'total' => '$ 115.000,00',
                    ],
                    'items' => [
                        [
                            'codigo' => 'SKU-001',
                            'descripcion' => 'Articulo demo principal',
                            'cantidad' => '2',
                            'precio_unitario' => '$ 25.000,00',
                            'bonificacion' => '0 %',
                            'importe' => '$ 50.000,00',
                        ],
                        [
                            'codigo' => 'SKU-002',
                            'descripcion' => 'Segundo item para preview',
                            'cantidad' => '1',
                            'precio_unitario' => '$ 65.000,00',
                            'bonificacion' => '7,69 %',
                            'importe' => '$ 60.000,00',
                        ],
                    ],
                ],
            ],
            // ---------------------------------------------------------------
            // PDS — Pedido de Servicio CRM
            // ---------------------------------------------------------------
            [
                'document_key' => 'crm_pds',
                'area'         => 'crm',
                'label'        => 'Pedido de Servicio CRM',
                'description'  => 'Formulario imprimible del pedido de servicio: empresa, cliente, artículo, tiempos y diagnóstico técnico.',
                'default_page_config' => [
                    'page' => [
                        'size'           => 'A4',
                        'orientation'    => 'portrait',
                        'width_mm'       => 210,
                        'height_mm'      => 297,
                        'margin_top_mm'  => 0,
                        'margin_right_mm'  => 0,
                        'margin_bottom_mm' => 0,
                        'margin_left_mm'   => 0,
                    ],
                    'grid' => [
                        'enabled' => true,
                        'step_mm' => 2,
                        'snap'    => true,
                    ],
                    'background' => [
                        'asset_id' => null,
                        'opacity'  => 1,
                    ],
                    'defaults' => [
                        'font_family'  => 'Arial, Helvetica, sans-serif',
                        'font_size_pt' => 10,
                        'color'        => '#111111',
                    ],
                ],
                'default_objects' => [
                    // ---- Título y número ----
                    [
                        'id'      => 'obj_pds_title',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 12,
                        'w_mm'    => 100,
                        'h_mm'    => 8,
                        'z_index' => 10,
                        'content' => 'PEDIDO DE SERVICIO',
                        'style'   => [
                            'font_family'  => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 15,
                            'font_weight'  => 700,
                            'color'        => '#111111',
                            'align'        => 'left',
                        ],
                    ],
                    [
                        'id'     => 'obj_pds_numero',
                        'type'   => 'variable',
                        'x_mm'   => 140,
                        'y_mm'   => 12,
                        'w_mm'   => 58,
                        'h_mm'   => 8,
                        'z_index' => 11,
                        'source' => 'pedido.numero',
                        'style'  => [
                            'font_family'  => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 14,
                            'font_weight'  => 700,
                            'color'        => '#111111',
                            'align'        => 'right',
                        ],
                    ],
                    // ---- Separador header ----
                    [
                        'id'     => 'obj_sep_header',
                        'type'   => 'line',
                        'x_mm'   => 10,
                        'y_mm'   => 22,
                        'w_mm'   => 190,
                        'h_mm'   => 0,
                        'z_index' => 5,
                        'style'  => ['stroke' => '#1f2937', 'stroke_width_mm' => 0.35],
                    ],
                    // ---- Empresa ----
                    [
                        'id'      => 'obj_empresa_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 26,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Empresa:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_empresa_nombre',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 26,
                        'w_mm'   => 90,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'empresa.nombre',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_empresa_cuit_label',
                        'type'    => 'text',
                        'x_mm'    => 140,
                        'y_mm'    => 26,
                        'w_mm'    => 18,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'CUIT:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_empresa_cuit',
                        'type'   => 'variable',
                        'x_mm'   => 158,
                        'y_mm'   => 26,
                        'w_mm'   => 40,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'empresa.cuit',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    // ---- Separador cliente ----
                    [
                        'id'     => 'obj_sep_cliente',
                        'type'   => 'line',
                        'x_mm'   => 10,
                        'y_mm'   => 35,
                        'w_mm'   => 190,
                        'h_mm'   => 0,
                        'z_index' => 5,
                        'style'  => ['stroke' => '#d1d5db', 'stroke_width_mm' => 0.2],
                    ],
                    // ---- Cliente ----
                    [
                        'id'      => 'obj_cliente_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 38,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Cliente:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_cliente_nombre',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 38,
                        'w_mm'   => 90,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'cliente.nombre',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_cliente_doc_label',
                        'type'    => 'text',
                        'x_mm'    => 140,
                        'y_mm'    => 38,
                        'w_mm'    => 18,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Doc:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_cliente_doc',
                        'type'   => 'variable',
                        'x_mm'   => 158,
                        'y_mm'   => 38,
                        'w_mm'   => 40,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'cliente.documento',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    // ---- Separador técnico ----
                    [
                        'id'     => 'obj_sep_tecnico',
                        'type'   => 'line',
                        'x_mm'   => 10,
                        'y_mm'   => 47,
                        'w_mm'   => 190,
                        'h_mm'   => 0,
                        'z_index' => 5,
                        'style'  => ['stroke' => '#d1d5db', 'stroke_width_mm' => 0.2],
                    ],
                    // ---- Cabecera técnica ----
                    [
                        'id'      => 'obj_solicito_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 50,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Solicitó:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_solicito',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 50,
                        'w_mm'   => 70,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'pedido.solicito',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_clasificacion_label',
                        'type'    => 'text',
                        'x_mm'    => 115,
                        'y_mm'    => 50,
                        'w_mm'    => 28,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Clasificación:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_clasificacion',
                        'type'   => 'variable',
                        'x_mm'   => 143,
                        'y_mm'   => 50,
                        'w_mm'   => 55,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'pedido.clasificacion',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_articulo_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 58,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Artículo:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_articulo_nombre',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 58,
                        'w_mm'   => 100,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'articulo.nombre',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_articulo_cod_label',
                        'type'    => 'text',
                        'x_mm'    => 140,
                        'y_mm'    => 58,
                        'w_mm'    => 18,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Cód:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_articulo_codigo',
                        'type'   => 'variable',
                        'x_mm'   => 158,
                        'y_mm'   => 58,
                        'w_mm'   => 40,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'articulo.codigo',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    // ---- Separador tiempos ----
                    [
                        'id'     => 'obj_sep_tiempos',
                        'type'   => 'line',
                        'x_mm'   => 10,
                        'y_mm'   => 68,
                        'w_mm'   => 190,
                        'h_mm'   => 0,
                        'z_index' => 5,
                        'style'  => ['stroke' => '#d1d5db', 'stroke_width_mm' => 0.2],
                    ],
                    // ---- Bloque tiempos ----
                    [
                        'id'      => 'obj_tiempos_title',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 72,
                        'w_mm'    => 60,
                        'h_mm'    => 5,
                        'z_index' => 10,
                        'content' => 'TIEMPOS DE SERVICIO',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 8, 'font_weight' => 700, 'color' => '#6b7280', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_inicio_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 79,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Inicio:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_inicio',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 79,
                        'w_mm'   => 55,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'pedido.fecha_inicio',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_fin_label',
                        'type'    => 'text',
                        'x_mm'    => 100,
                        'y_mm'    => 79,
                        'w_mm'    => 30,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Finalizado:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_fin',
                        'type'   => 'variable',
                        'x_mm'   => 130,
                        'y_mm'   => 79,
                        'w_mm'   => 68,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'pedido.fecha_finalizado',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_bruto_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 87,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'T. bruto:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_bruto',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 87,
                        'w_mm'   => 35,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'tiempos.duracion_bruta',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_descuento_label',
                        'type'    => 'text',
                        'x_mm'    => 80,
                        'y_mm'    => 87,
                        'w_mm'    => 22,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Descuento:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_descuento',
                        'type'   => 'variable',
                        'x_mm'   => 102,
                        'y_mm'   => 87,
                        'w_mm'   => 30,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'tiempos.descuento',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_neto_label',
                        'type'    => 'text',
                        'x_mm'    => 140,
                        'y_mm'    => 87,
                        'w_mm'    => 18,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'T. neto:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_neto',
                        'type'   => 'variable',
                        'x_mm'   => 158,
                        'y_mm'   => 87,
                        'w_mm'   => 40,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'tiempos.duracion_neta',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#15803d', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_decimal_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 95,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Horas dec.:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_decimal',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 95,
                        'w_mm'   => 40,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'tiempos.decimal',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#1d4ed8', 'align' => 'left'],
                    ],
                    // ---- Separador diagnóstico ----
                    [
                        'id'     => 'obj_sep_diag',
                        'type'   => 'line',
                        'x_mm'   => 10,
                        'y_mm'   => 105,
                        'w_mm'   => 190,
                        'h_mm'   => 0,
                        'z_index' => 5,
                        'style'  => ['stroke' => '#d1d5db', 'stroke_width_mm' => 0.2],
                    ],
                    // ---- Motivo de Descuento ----
                    [
                        'id'      => 'obj_motivo_desc_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 108,
                        'w_mm'    => 35,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Motivo de Descuento:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_motivo_desc',
                        'type'   => 'variable',
                        'x_mm'   => 47,
                        'y_mm'   => 108,
                        'w_mm'   => 151,
                        'h_mm'   => 14,
                        'z_index' => 10,
                        'source' => 'pedido.motivo_descuento',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    // ---- Diagnóstico ----
                    [
                        'id'      => 'obj_diag_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 126,
                        'w_mm'    => 25,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Diagnóstico:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_diagnostico',
                        'type'   => 'variable',
                        'x_mm'   => 37,
                        'y_mm'   => 126,
                        'w_mm'   => 161,
                        'h_mm'   => 40,
                        'z_index' => 10,
                        'source' => 'pedido.diagnostico',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                    // ---- Footer ----
                    [
                        'id'     => 'obj_footer_box',
                        'type'   => 'rect',
                        'x_mm'   => 10,
                        'y_mm'   => 272,
                        'w_mm'   => 190,
                        'h_mm'   => 20,
                        'z_index' => 2,
                        'style'  => ['stroke' => '#94a3b8', 'stroke_width_mm' => 0.3, 'fill' => 'transparent'],
                    ],
                    [
                        'id'      => 'obj_estado_label',
                        'type'    => 'text',
                        'x_mm'    => 12,
                        'y_mm'    => 278,
                        'w_mm'    => 20,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Estado:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_estado',
                        'type'   => 'variable',
                        'x_mm'   => 32,
                        'y_mm'   => 278,
                        'w_mm'   => 40,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'pedido.estado',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#15803d', 'align' => 'left'],
                    ],
                    [
                        'id'      => 'obj_nro_tango_label',
                        'type'    => 'text',
                        'x_mm'    => 100,
                        'y_mm'    => 278,
                        'w_mm'    => 35,
                        'h_mm'    => 6,
                        'z_index' => 10,
                        'content' => 'Nro Tango:',
                        'style'   => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 700, 'color' => '#374151', 'align' => 'left'],
                    ],
                    [
                        'id'     => 'obj_nro_tango',
                        'type'   => 'variable',
                        'x_mm'   => 135,
                        'y_mm'   => 278,
                        'w_mm'   => 63,
                        'h_mm'   => 6,
                        'z_index' => 10,
                        'source' => 'pedido.nro_pedido_tango',
                        'style'  => ['font_family' => 'Arial, Helvetica, sans-serif', 'font_size_pt' => 9, 'font_weight' => 400, 'color' => '#111111', 'align' => 'left'],
                    ],
                ],
                'variables' => [
                    [
                        'group' => 'Empresa',
                        'items' => [
                            ['source' => 'empresa.nombre', 'label' => 'Empresa / Nombre'],
                            ['source' => 'empresa.cuit',   'label' => 'Empresa / CUIT'],
                            ['source' => 'empresa.header_url', 'label' => 'Empresa / Header (Imagen)'],
                            ['source' => 'empresa.footer_url', 'label' => 'Empresa / Footer (Imagen)'],
                        ],
                    ],
                    [
                        'group' => 'Cliente',
                        'items' => [
                            ['source' => 'cliente.nombre',    'label' => 'Cliente / Nombre'],
                            ['source' => 'cliente.documento', 'label' => 'Cliente / Documento'],
                            ['source' => 'cliente.email',     'label' => 'Cliente / Email'],
                        ],
                    ],
                    [
                        'group' => 'Artículo',
                        'items' => [
                            ['source' => 'articulo.codigo', 'label' => 'Artículo / Código'],
                            ['source' => 'articulo.nombre', 'label' => 'Artículo / Nombre'],
                            ['source' => 'articulo.precio', 'label' => 'Artículo / Precio unitario'],
                        ],
                    ],
                    [
                        'group' => 'Pedido',
                        'items' => [
                            ['source' => 'pedido.numero',           'label' => 'Pedido / Número'],
                            ['source' => 'pedido.solicito',         'label' => 'Pedido / Solicitó'],
                            ['source' => 'pedido.usuario',          'label' => 'Pedido / Usuario (Creador)'],
                            ['source' => 'pedido.fecha_inicio',     'label' => 'Pedido / Fecha inicio'],
                            ['source' => 'pedido.fecha_finalizado', 'label' => 'Pedido / Fecha finalizado'],
                            ['source' => 'pedido.clasificacion',    'label' => 'Pedido / Clasificación'],
                            ['source' => 'pedido.nro_pedido_tango', 'label' => 'Pedido / Nro Tango'],
                            ['source' => 'pedido.motivo_descuento',            'label' => 'Pedido / Motivo Desc.'],
                            ['source' => 'pedido.diagnostico',      'label' => 'Pedido / Diagnóstico'],
                            ['source' => 'pedido.estado',           'label' => 'Pedido / Estado'],
                        ],
                    ],
                    [
                        'group' => 'Tiempos',
                        'items' => [
                            ['source' => 'tiempos.duracion_bruta', 'label' => 'Tiempos / Bruto (HH:MM:SS)'],
                            ['source' => 'tiempos.descuento',      'label' => 'Tiempos / Descuento (HH:MM:SS)'],
                            ['source' => 'tiempos.duracion_neta',  'label' => 'Tiempos / Neto (HH:MM:SS)'],
                            ['source' => 'tiempos.decimal',        'label' => 'Tiempos / Decimal (horas)'],
                        ],
                    ],
                ],
                'repeaters'      => [],
                'sample_context' => [
                    'empresa' => [
                        'nombre'     => 'RXN Demo S.A.',
                        'cuit'       => '30-12345678-9',
                        'header_url' => 'https://placehold.co/800x200?text=Header+Logo',
                        'footer_url' => 'https://placehold.co/800x100?text=Footer+Logo',
                    ],
                    'cliente' => [
                        'nombre'    => 'Cliente Demo',
                        'documento' => '20-30111222-3',
                        'email'     => 'cliente@demo.com',
                    ],
                    'articulo' => [
                        'codigo' => 'SKU-001',
                        'nombre' => 'Servicio técnico equipo demo',
                        'precio' => '$ 18.000,00',
                    ],
                    'pedido' => [
                        'numero'            => '000042',
                        'solicito'          => 'María López',
                        'fecha_inicio'      => '30/03/2026 09:00',
                        'fecha_finalizado'  => '30/03/2026 11:30',
                        'clasificacion'     => 'RPR — Reparación en taller',
                        'nro_pedido_tango'  => '000001',
                        'motivo_descuento'             => 'Usuario de primera vez, promo referidos.',
                        'diagnostico'       => 'Se detectó cortocircuito en la placa fuente. Se reemplazó el componente R47 y se realizó prueba de carga completa.',
                        'estado'            => 'Finalizado',
                    ],
                    'tiempos' => [
                        'duracion_bruta' => '02:30:00',
                        'descuento'      => '00:15:00',
                        'duracion_neta'  => '02:15:00',
                        'decimal'        => '2,25 hs',
                    ],
                ],
            ],
            // ---------------------------------------------------------------
            // Presupuesto — Cuerpo Email
            // ---------------------------------------------------------------
            [
                'document_key' => 'crm_presupuesto_email',
                'area' => 'crm',
                'label' => 'Presupuesto (Cuerpo Email)',
                'description' => 'Plantilla para el cuerpo del correo de presupuestos.',
                'default_page_config' => [
                    'page' => [
                        'size' => 'A4',
                        'orientation' => 'portrait',
                        'width_mm' => 210,
                        'height_mm' => 297,
                        'margin_top_mm' => 0,
                        'margin_right_mm' => 0,
                        'margin_bottom_mm' => 0,
                        'margin_left_mm' => 0,
                    ],
                    'grid' => [
                        'enabled' => true,
                        'step_mm' => 2,
                        'snap' => true,
                    ],
                    'background' => [
                        'asset_id' => null,
                        'opacity' => 1,
                    ],
                    'defaults' => [
                        'font_family' => 'Arial, Helvetica, sans-serif',
                        'font_size_pt' => 12,
                        'color' => '#111111',
                    ],
                ],
                'default_objects' => [
                    [
                        'id' => 'obj_title_text',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 12,
                        'w_mm' => 180,
                        'h_mm' => 8,
                        'z_index' => 10,
                        'content' => 'Acá tenés tu presupuesto...',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 16,
                            'font_weight' => 700,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_body_text',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 30,
                        'w_mm' => 180,
                        'h_mm' => 20,
                        'z_index' => 10,
                        'content' => 'Hola estimado, adjunto a este correo encontrarás el presupuesto solicitado. Saludos cordiales.',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 12,
                            'font_weight' => 400,
                            'color' => '#333333',
                            'align' => 'left',
                        ],
                    ],
                ],
                // Mismas variables que el presupuesto normal
                'variables' => [
                    [
                        'group' => 'Empresa',
                        'items' => [
                            ['source' => 'empresa.nombre', 'label' => 'Empresa / Nombre'],
                            ['source' => 'empresa.cuit', 'label' => 'Empresa / CUIT'],
                            ['source' => 'empresa.header_url', 'label' => 'Empresa / Header (Imagen)'],
                            ['source' => 'empresa.footer_url', 'label' => 'Empresa / Footer (Imagen)'],
                        ],
                    ],
                    [
                        'group' => 'Cliente',
                        'items' => [
                            ['source' => 'cliente.nombre', 'label' => 'Cliente / Nombre'],
                            ['source' => 'cliente.documento', 'label' => 'Cliente / Documento'],
                        ],
                    ],
                    [
                        'group' => 'Presupuesto',
                        'items' => [
                            ['source' => 'presupuesto.numero', 'label' => 'Presupuesto / Numero'],
                            ['source' => 'presupuesto.fecha', 'label' => 'Presupuesto / Fecha'],
                        ],
                    ],
                    [
                        'group' => 'Totales',
                        'items' => [
                            ['source' => 'totales.subtotal', 'label' => 'Totales / Subtotal'],
                            ['source' => 'totales.descuento', 'label' => 'Totales / Descuento'],
                            ['source' => 'totales.total', 'label' => 'Totales / Total'],
                        ],
                    ],
                ],
                'repeaters' => [
                    [
                        'source' => 'items[]',
                        'label' => 'Renglones / Items[]',
                        'description' => 'Bloque repetitivo para detalle comercial del presupuesto.',
                    ],
                ],
                'sample_context' => [
                    'empresa' => [
                        'nombre'     => 'RXN Demo',
                        'cuit'       => '30-12345678-9',
                        'header_url' => 'https://placehold.co/800x200?text=Header+Logo',
                        'footer_url' => 'https://placehold.co/800x100?text=Footer+Logo',
                    ],
                    'cliente' => [
                        'nombre' => 'Cliente Demo S.A.',
                        'documento' => '20-30111222-3',
                    ],
                    'presupuesto' => [
                        'numero' => '000123',
                        'fecha' => '28/03/2026',
                    ],
                    'totales' => [
                        'subtotal' => '$ 120.000,00',
                        'descuento' => '$ 5.000,00',
                        'total' => '$ 115.000,00',
                    ],
                    'items' => [],
                ],
            ],
            // ---------------------------------------------------------------
            // PDS — Cuerpo Email
            // ---------------------------------------------------------------
            [
                'document_key' => 'crm_pds_email',
                'area' => 'crm',
                'label' => 'PDS (Cuerpo Email)',
                'description' => 'Plantilla para el cuerpo del correo de Pedidos de Servicio.',
                'default_page_config' => [
                    'page' => [
                        'size' => 'A4',
                        'orientation' => 'portrait',
                        'width_mm' => 210,
                        'height_mm' => 297,
                        'margin_top_mm' => 0,
                        'margin_right_mm' => 0,
                        'margin_bottom_mm' => 0,
                        'margin_left_mm' => 0,
                    ],
                    'grid' => [
                        'enabled' => true,
                        'step_mm' => 2,
                        'snap' => true,
                    ],
                    'background' => [
                        'asset_id' => null,
                        'opacity' => 1,
                    ],
                    'defaults' => [
                        'font_family' => 'Arial, Helvetica, sans-serif',
                        'font_size_pt' => 12,
                        'color' => '#111111',
                    ],
                ],
                'default_objects' => [
                    [
                        'id' => 'obj_title_text',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 12,
                        'w_mm' => 180,
                        'h_mm' => 8,
                        'z_index' => 10,
                        'content' => 'Estado de su servicio...',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 16,
                            'font_weight' => 700,
                            'color' => '#111111',
                            'align' => 'left',
                        ],
                    ],
                    [
                        'id' => 'obj_body_text',
                        'type' => 'text',
                        'x_mm' => 12,
                        'y_mm' => 30,
                        'w_mm' => 180,
                        'h_mm' => 20,
                        'z_index' => 10,
                        'content' => 'Hola estimado, adjuntamos la constancia de su pedido de servicio. Saludos cordiales.',
                        'style' => [
                            'font_family' => 'Arial, Helvetica, sans-serif',
                            'font_size_pt' => 12,
                            'font_weight' => 400,
                            'color' => '#333333',
                            'align' => 'left',
                        ],
                    ],
                ],
                // Mismas variables que el PDS normal
                'variables' => [
                    [
                        'group' => 'Empresa',
                        'items' => [
                            ['source' => 'empresa.nombre', 'label' => 'Empresa / Nombre'],
                            ['source' => 'empresa.cuit',   'label' => 'Empresa / CUIT'],
                            ['source' => 'empresa.header_url', 'label' => 'Empresa / Header (Imagen)'],
                            ['source' => 'empresa.footer_url', 'label' => 'Empresa / Footer (Imagen)'],
                        ],
                    ],
                    [
                        'group' => 'Cliente',
                        'items' => [
                            ['source' => 'cliente.nombre',    'label' => 'Cliente / Nombre'],
                            ['source' => 'cliente.documento', 'label' => 'Cliente / Documento'],
                            ['source' => 'cliente.email',     'label' => 'Cliente / Email'],
                        ],
                    ],
                    [
                        'group' => 'Artículo',
                        'items' => [
                            ['source' => 'articulo.codigo', 'label' => 'Artículo / Código'],
                            ['source' => 'articulo.nombre', 'label' => 'Artículo / Nombre'],
                            ['source' => 'articulo.precio', 'label' => 'Artículo / Precio unitario'],
                        ],
                    ],
                    [
                        'group' => 'Pedido',
                        'items' => [
                            ['source' => 'pedido.numero',           'label' => 'Pedido / Número'],
                            ['source' => 'pedido.solicito',         'label' => 'Pedido / Solicitó'],
                            ['source' => 'pedido.fecha_inicio',     'label' => 'Pedido / Fecha inicio'],
                            ['source' => 'pedido.fecha_finalizado', 'label' => 'Pedido / Fecha finalizado'],
                            ['source' => 'pedido.clasificacion',    'label' => 'Pedido / Clasificación'],
                            ['source' => 'pedido.nro_pedido_tango', 'label' => 'Pedido / Nro Tango'],
                            ['source' => 'pedido.motivo_descuento',            'label' => 'Pedido / Motivo Desc.'],
                            ['source' => 'pedido.diagnostico',      'label' => 'Pedido / Diagnóstico'],
                            ['source' => 'pedido.estado',           'label' => 'Pedido / Estado'],
                        ],
                    ],
                    [
                        'group' => 'Tiempos',
                        'items' => [
                            ['source' => 'tiempos.duracion_bruta', 'label' => 'Tiempos / Bruto (HH:MM:SS)'],
                            ['source' => 'tiempos.descuento',      'label' => 'Tiempos / Descuento (HH:MM:SS)'],
                            ['source' => 'tiempos.duracion_neta',  'label' => 'Tiempos / Neto (HH:MM:SS)'],
                            ['source' => 'tiempos.decimal',        'label' => 'Tiempos / Decimal (horas)'],
                        ],
                    ],
                ],
                'repeaters'      => [],
                'sample_context' => [
                    'empresa' => [
                        'nombre'     => 'RXN Demo S.A.',
                        'cuit'       => '30-12345678-9',
                        'header_url' => 'https://placehold.co/800x200?text=Header+Logo',
                        'footer_url' => 'https://placehold.co/800x100?text=Footer+Logo',
                    ],
                    'cliente' => [
                        'nombre'    => 'Cliente Demo',
                        'documento' => '20-30111222-3',
                        'email'     => 'cliente@demo.com',
                    ],
                    'articulo' => [
                        'codigo' => 'SKU-001',
                        'nombre' => 'Servicio técnico equipo demo',
                        'precio' => '$ 18.000,00',
                    ],
                    'pedido' => [
                        'numero'            => '000042',
                        'solicito'          => 'María López',
                        'fecha_inicio'      => '30/03/2026 09:00',
                        'fecha_finalizado'  => '30/03/2026 11:30',
                        'clasificacion'     => 'RPR — Reparación en taller',
                        'nro_pedido_tango'  => '000001',
                        'motivo_descuento'             => 'Usuario de primera vez, promo referidos.',
                        'diagnostico'       => 'Se detectó cortocircuito en la placa fuente. Se reemplazó el componente R47 y se realizó prueba de carga completa.',
                        'estado'            => 'Finalizado',
                    ],
                    'tiempos' => [
                        'duracion_bruta' => '02:30:00',
                        'descuento'      => '00:15:00',
                        'duracion_neta'  => '02:15:00',
                        'decimal'        => '2,25 hs',
                    ],
                ],
            ],
        ];
    }
}
